# Copyright 2021 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build the manager binary
ARG GO_VERSION
ARG OS_CODENAME
FROM golang:${GO_VERSION}-${OS_CODENAME} as builder

WORKDIR /go/src/sigs.k8s.io/k8s-container-image-promoter

# Copy the sources
ENV package="./cmd/kpromo"

# TODO(kpromo): Consider restricting the files copied in after refactor
COPY . ./

RUN go mod download

# Build
ARG ARCH

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=${ARCH}

RUN go build -trimpath -ldflags '-s -w -buildid= -extldflags "-static"' \
    -o kpromo ${package}

# Production image
FROM gcr.io/google.com/cloudsdktool/cloud-sdk:slim

LABEL maintainers="Kubernetes Authors"
LABEL description="kpromo: The Kubernetes project artifact promoter"

WORKDIR /
COPY --from=builder /go/src/sigs.k8s.io/k8s-container-image-promoter/kpromo .

ENTRYPOINT ["/kpromo"]
