/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"context"
	"sync"

	"sigs.k8s.io/promo-tools/v4/promoter/image/auth"
)

type FakeServiceActivator struct {
	ActivateServiceAccountsStub        func(context.Context, string) error
	activateServiceAccountsMutex       sync.RWMutex
	activateServiceAccountsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	activateServiceAccountsReturns struct {
		result1 error
	}
	activateServiceAccountsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceActivator) ActivateServiceAccounts(arg1 context.Context, arg2 string) error {
	fake.activateServiceAccountsMutex.Lock()
	ret, specificReturn := fake.activateServiceAccountsReturnsOnCall[len(fake.activateServiceAccountsArgsForCall)]
	fake.activateServiceAccountsArgsForCall = append(fake.activateServiceAccountsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ActivateServiceAccountsStub
	fakeReturns := fake.activateServiceAccountsReturns
	fake.recordInvocation("ActivateServiceAccounts", []interface{}{arg1, arg2})
	fake.activateServiceAccountsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeServiceActivator) ActivateServiceAccountsCallCount() int {
	fake.activateServiceAccountsMutex.RLock()
	defer fake.activateServiceAccountsMutex.RUnlock()
	return len(fake.activateServiceAccountsArgsForCall)
}

func (fake *FakeServiceActivator) ActivateServiceAccountsCalls(stub func(context.Context, string) error) {
	fake.activateServiceAccountsMutex.Lock()
	defer fake.activateServiceAccountsMutex.Unlock()
	fake.ActivateServiceAccountsStub = stub
}

func (fake *FakeServiceActivator) ActivateServiceAccountsArgsForCall(i int) (context.Context, string) {
	fake.activateServiceAccountsMutex.RLock()
	defer fake.activateServiceAccountsMutex.RUnlock()
	argsForCall := fake.activateServiceAccountsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeServiceActivator) ActivateServiceAccountsReturns(result1 error) {
	fake.activateServiceAccountsMutex.Lock()
	defer fake.activateServiceAccountsMutex.Unlock()
	fake.ActivateServiceAccountsStub = nil
	fake.activateServiceAccountsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceActivator) ActivateServiceAccountsReturnsOnCall(i int, result1 error) {
	fake.activateServiceAccountsMutex.Lock()
	defer fake.activateServiceAccountsMutex.Unlock()
	fake.ActivateServiceAccountsStub = nil
	if fake.activateServiceAccountsReturnsOnCall == nil {
		fake.activateServiceAccountsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.activateServiceAccountsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceActivator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceActivator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.ServiceActivator = new(FakeServiceActivator)
