/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"context"
	"sync"

	"sigs.k8s.io/promo-tools/v4/promoter/image/auth"
)

type FakeIdentityTokenProvider struct {
	GetIdentityTokenStub        func(context.Context, string, string) (string, error)
	getIdentityTokenMutex       sync.RWMutex
	getIdentityTokenArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getIdentityTokenReturns struct {
		result1 string
		result2 error
	}
	getIdentityTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIdentityTokenProvider) GetIdentityToken(arg1 context.Context, arg2 string, arg3 string) (string, error) {
	fake.getIdentityTokenMutex.Lock()
	ret, specificReturn := fake.getIdentityTokenReturnsOnCall[len(fake.getIdentityTokenArgsForCall)]
	fake.getIdentityTokenArgsForCall = append(fake.getIdentityTokenArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetIdentityTokenStub
	fakeReturns := fake.getIdentityTokenReturns
	fake.recordInvocation("GetIdentityToken", []interface{}{arg1, arg2, arg3})
	fake.getIdentityTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIdentityTokenProvider) GetIdentityTokenCallCount() int {
	fake.getIdentityTokenMutex.RLock()
	defer fake.getIdentityTokenMutex.RUnlock()
	return len(fake.getIdentityTokenArgsForCall)
}

func (fake *FakeIdentityTokenProvider) GetIdentityTokenCalls(stub func(context.Context, string, string) (string, error)) {
	fake.getIdentityTokenMutex.Lock()
	defer fake.getIdentityTokenMutex.Unlock()
	fake.GetIdentityTokenStub = stub
}

func (fake *FakeIdentityTokenProvider) GetIdentityTokenArgsForCall(i int) (context.Context, string, string) {
	fake.getIdentityTokenMutex.RLock()
	defer fake.getIdentityTokenMutex.RUnlock()
	argsForCall := fake.getIdentityTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeIdentityTokenProvider) GetIdentityTokenReturns(result1 string, result2 error) {
	fake.getIdentityTokenMutex.Lock()
	defer fake.getIdentityTokenMutex.Unlock()
	fake.GetIdentityTokenStub = nil
	fake.getIdentityTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeIdentityTokenProvider) GetIdentityTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.getIdentityTokenMutex.Lock()
	defer fake.getIdentityTokenMutex.Unlock()
	fake.GetIdentityTokenStub = nil
	if fake.getIdentityTokenReturnsOnCall == nil {
		fake.getIdentityTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getIdentityTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeIdentityTokenProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIdentityTokenProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.IdentityTokenProvider = new(FakeIdentityTokenProvider)
