/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package registryfakes

import (
	"context"
	"sync"

	"sigs.k8s.io/promo-tools/v4/promoter/image/registry"
)

type FakeProvider struct {
	CopyImageStub        func(context.Context, string, string) error
	copyImageMutex       sync.RWMutex
	copyImageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	copyImageReturns struct {
		result1 error
	}
	copyImageReturnsOnCall map[int]struct {
		result1 error
	}
	ReadRegistriesStub        func(context.Context, []registry.RegistryConfig, bool, []registry.RegistryConfig) (*registry.Inventory, error)
	readRegistriesMutex       sync.RWMutex
	readRegistriesArgsForCall []struct {
		arg1 context.Context
		arg2 []registry.RegistryConfig
		arg3 bool
		arg4 []registry.RegistryConfig
	}
	readRegistriesReturns struct {
		result1 *registry.Inventory
		result2 error
	}
	readRegistriesReturnsOnCall map[int]struct {
		result1 *registry.Inventory
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) CopyImage(arg1 context.Context, arg2 string, arg3 string) error {
	fake.copyImageMutex.Lock()
	ret, specificReturn := fake.copyImageReturnsOnCall[len(fake.copyImageArgsForCall)]
	fake.copyImageArgsForCall = append(fake.copyImageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CopyImageStub
	fakeReturns := fake.copyImageReturns
	fake.recordInvocation("CopyImage", []interface{}{arg1, arg2, arg3})
	fake.copyImageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProvider) CopyImageCallCount() int {
	fake.copyImageMutex.RLock()
	defer fake.copyImageMutex.RUnlock()
	return len(fake.copyImageArgsForCall)
}

func (fake *FakeProvider) CopyImageCalls(stub func(context.Context, string, string) error) {
	fake.copyImageMutex.Lock()
	defer fake.copyImageMutex.Unlock()
	fake.CopyImageStub = stub
}

func (fake *FakeProvider) CopyImageArgsForCall(i int) (context.Context, string, string) {
	fake.copyImageMutex.RLock()
	defer fake.copyImageMutex.RUnlock()
	argsForCall := fake.copyImageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProvider) CopyImageReturns(result1 error) {
	fake.copyImageMutex.Lock()
	defer fake.copyImageMutex.Unlock()
	fake.CopyImageStub = nil
	fake.copyImageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProvider) CopyImageReturnsOnCall(i int, result1 error) {
	fake.copyImageMutex.Lock()
	defer fake.copyImageMutex.Unlock()
	fake.CopyImageStub = nil
	if fake.copyImageReturnsOnCall == nil {
		fake.copyImageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.copyImageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProvider) ReadRegistries(arg1 context.Context, arg2 []registry.RegistryConfig, arg3 bool, arg4 []registry.RegistryConfig) (*registry.Inventory, error) {
	var arg2Copy []registry.RegistryConfig
	if arg2 != nil {
		arg2Copy = make([]registry.RegistryConfig, len(arg2))
		copy(arg2Copy, arg2)
	}
	var arg4Copy []registry.RegistryConfig
	if arg4 != nil {
		arg4Copy = make([]registry.RegistryConfig, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.readRegistriesMutex.Lock()
	ret, specificReturn := fake.readRegistriesReturnsOnCall[len(fake.readRegistriesArgsForCall)]
	fake.readRegistriesArgsForCall = append(fake.readRegistriesArgsForCall, struct {
		arg1 context.Context
		arg2 []registry.RegistryConfig
		arg3 bool
		arg4 []registry.RegistryConfig
	}{arg1, arg2Copy, arg3, arg4Copy})
	stub := fake.ReadRegistriesStub
	fakeReturns := fake.readRegistriesReturns
	fake.recordInvocation("ReadRegistries", []interface{}{arg1, arg2Copy, arg3, arg4Copy})
	fake.readRegistriesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) ReadRegistriesCallCount() int {
	fake.readRegistriesMutex.RLock()
	defer fake.readRegistriesMutex.RUnlock()
	return len(fake.readRegistriesArgsForCall)
}

func (fake *FakeProvider) ReadRegistriesCalls(stub func(context.Context, []registry.RegistryConfig, bool, []registry.RegistryConfig) (*registry.Inventory, error)) {
	fake.readRegistriesMutex.Lock()
	defer fake.readRegistriesMutex.Unlock()
	fake.ReadRegistriesStub = stub
}

func (fake *FakeProvider) ReadRegistriesArgsForCall(i int) (context.Context, []registry.RegistryConfig, bool, []registry.RegistryConfig) {
	fake.readRegistriesMutex.RLock()
	defer fake.readRegistriesMutex.RUnlock()
	argsForCall := fake.readRegistriesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProvider) ReadRegistriesReturns(result1 *registry.Inventory, result2 error) {
	fake.readRegistriesMutex.Lock()
	defer fake.readRegistriesMutex.Unlock()
	fake.ReadRegistriesStub = nil
	fake.readRegistriesReturns = struct {
		result1 *registry.Inventory
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) ReadRegistriesReturnsOnCall(i int, result1 *registry.Inventory, result2 error) {
	fake.readRegistriesMutex.Lock()
	defer fake.readRegistriesMutex.Unlock()
	fake.ReadRegistriesStub = nil
	if fake.readRegistriesReturnsOnCall == nil {
		fake.readRegistriesReturnsOnCall = make(map[int]struct {
			result1 *registry.Inventory
			result2 error
		})
	}
	fake.readRegistriesReturnsOnCall[i] = struct {
		result1 *registry.Inventory
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ registry.Provider = new(FakeProvider)
