#!/usr/bin/env python

# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage:
# Pipe output from sha256sum, produces file-manifest formatted output.

# For example:
# gsutil rsync -r gs://my-bucket download
# cd download
# find . -type f | sort | xargs sha256sum | ../dev/build-file-manifest

import sys

for line in sys.stdin:
  line = line.strip()
  tokens = line.split()
  if len(tokens) == 2:
    path = tokens[1]
    path = path[2:] if path.startswith("./") else path
    print("- name: %s" % (path))
    print("  sha256: %s" % (tokens[0]))
  else:
    print("# unknown: %s" % (line))
