/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package provenancefakes

import (
	"context"
	"sync"

	"sigs.k8s.io/promo-tools/v4/promoter/image/provenance"
)

type FakeDiscoverer struct {
	DiscoverStub        func(context.Context, string) (*provenance.Discovery, error)
	discoverMutex       sync.RWMutex
	discoverArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	discoverReturns struct {
		result1 *provenance.Discovery
		result2 error
	}
	discoverReturnsOnCall map[int]struct {
		result1 *provenance.Discovery
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDiscoverer) Discover(arg1 context.Context, arg2 string) (*provenance.Discovery, error) {
	fake.discoverMutex.Lock()
	ret, specificReturn := fake.discoverReturnsOnCall[len(fake.discoverArgsForCall)]
	fake.discoverArgsForCall = append(fake.discoverArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DiscoverStub
	fakeReturns := fake.discoverReturns
	fake.recordInvocation("Discover", []interface{}{arg1, arg2})
	fake.discoverMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDiscoverer) DiscoverCallCount() int {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	return len(fake.discoverArgsForCall)
}

func (fake *FakeDiscoverer) DiscoverCalls(stub func(context.Context, string) (*provenance.Discovery, error)) {
	fake.discoverMutex.Lock()
	defer fake.discoverMutex.Unlock()
	fake.DiscoverStub = stub
}

func (fake *FakeDiscoverer) DiscoverArgsForCall(i int) (context.Context, string) {
	fake.discoverMutex.RLock()
	defer fake.discoverMutex.RUnlock()
	argsForCall := fake.discoverArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDiscoverer) DiscoverReturns(result1 *provenance.Discovery, result2 error) {
	fake.discoverMutex.Lock()
	defer fake.discoverMutex.Unlock()
	fake.DiscoverStub = nil
	fake.discoverReturns = struct {
		result1 *provenance.Discovery
		result2 error
	}{result1, result2}
}

func (fake *FakeDiscoverer) DiscoverReturnsOnCall(i int, result1 *provenance.Discovery, result2 error) {
	fake.discoverMutex.Lock()
	defer fake.discoverMutex.Unlock()
	fake.DiscoverStub = nil
	if fake.discoverReturnsOnCall == nil {
		fake.discoverReturnsOnCall = make(map[int]struct {
			result1 *provenance.Discovery
			result2 error
		})
	}
	fake.discoverReturnsOnCall[i] = struct {
		result1 *provenance.Discovery
		result2 error
	}{result1, result2}
}

func (fake *FakeDiscoverer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDiscoverer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ provenance.Discoverer = new(FakeDiscoverer)
