/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package imagefakes

import (
	"sync"

	"sigs.k8s.io/promo-tools/v4/promoter/image/checkresults"
	imagepromotera "sigs.k8s.io/promo-tools/v4/promoter/image/options"
	"sigs.k8s.io/promo-tools/v4/promoter/image/promotion"
	"sigs.k8s.io/promo-tools/v4/promoter/image/provenance"
	"sigs.k8s.io/promo-tools/v4/promoter/image/registry"
	"sigs.k8s.io/promo-tools/v4/promoter/image/schema"
)

type FakePromoterImplementation struct {
	ActivateServiceAccountsStub        func(*imagepromotera.Options) error
	activateServiceAccountsMutex       sync.RWMutex
	activateServiceAccountsArgsForCall []struct {
		arg1 *imagepromotera.Options
	}
	activateServiceAccountsReturns struct {
		result1 error
	}
	activateServiceAccountsReturnsOnCall map[int]struct {
		result1 error
	}
	AppendManifestToSnapshotStub        func(*imagepromotera.Options, []schema.Manifest) ([]schema.Manifest, error)
	appendManifestToSnapshotMutex       sync.RWMutex
	appendManifestToSnapshotArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 []schema.Manifest
	}
	appendManifestToSnapshotReturns struct {
		result1 []schema.Manifest
		result2 error
	}
	appendManifestToSnapshotReturnsOnCall map[int]struct {
		result1 []schema.Manifest
		result2 error
	}
	CopyFreshSignaturesStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	copyFreshSignaturesMutex       sync.RWMutex
	copyFreshSignaturesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}
	copyFreshSignaturesReturns struct {
		result1 error
	}
	copyFreshSignaturesReturnsOnCall map[int]struct {
		result1 error
	}
	EdgesFromManifestsStub        func([]schema.Manifest) (map[promotion.Edge]any, error)
	edgesFromManifestsMutex       sync.RWMutex
	edgesFromManifestsArgsForCall []struct {
		arg1 []schema.Manifest
	}
	edgesFromManifestsReturns struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	edgesFromManifestsReturnsOnCall map[int]struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	FixMissingSignaturesStub        func(*imagepromotera.Options, checkresults.Signature) error
	fixMissingSignaturesMutex       sync.RWMutex
	fixMissingSignaturesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 checkresults.Signature
	}
	fixMissingSignaturesReturns struct {
		result1 error
	}
	fixMissingSignaturesReturnsOnCall map[int]struct {
		result1 error
	}
	FixPartialSignaturesStub        func(*imagepromotera.Options, checkresults.Signature) error
	fixPartialSignaturesMutex       sync.RWMutex
	fixPartialSignaturesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 checkresults.Signature
	}
	fixPartialSignaturesReturns struct {
		result1 error
	}
	fixPartialSignaturesReturnsOnCall map[int]struct {
		result1 error
	}
	GetLatestImagesStub        func(*imagepromotera.Options) ([]string, error)
	getLatestImagesMutex       sync.RWMutex
	getLatestImagesArgsForCall []struct {
		arg1 *imagepromotera.Options
	}
	getLatestImagesReturns struct {
		result1 []string
		result2 error
	}
	getLatestImagesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	GetPromotionEdgesStub        func(*imagepromotera.Options, []schema.Manifest) (map[promotion.Edge]any, error)
	getPromotionEdgesMutex       sync.RWMutex
	getPromotionEdgesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 []schema.Manifest
	}
	getPromotionEdgesReturns struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	getPromotionEdgesReturnsOnCall map[int]struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	GetRegistryImageInventoryStub        func(*imagepromotera.Options, []schema.Manifest) (registry.RegInvImage, error)
	getRegistryImageInventoryMutex       sync.RWMutex
	getRegistryImageInventoryArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 []schema.Manifest
	}
	getRegistryImageInventoryReturns struct {
		result1 registry.RegInvImage
		result2 error
	}
	getRegistryImageInventoryReturnsOnCall map[int]struct {
		result1 registry.RegInvImage
		result2 error
	}
	GetSignatureStatusStub        func(*imagepromotera.Options, []string) (checkresults.Signature, error)
	getSignatureStatusMutex       sync.RWMutex
	getSignatureStatusArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 []string
	}
	getSignatureStatusReturns struct {
		result1 checkresults.Signature
		result2 error
	}
	getSignatureStatusReturnsOnCall map[int]struct {
		result1 checkresults.Signature
		result2 error
	}
	GetSnapshotManifestsStub        func(*imagepromotera.Options) ([]schema.Manifest, error)
	getSnapshotManifestsMutex       sync.RWMutex
	getSnapshotManifestsArgsForCall []struct {
		arg1 *imagepromotera.Options
	}
	getSnapshotManifestsReturns struct {
		result1 []schema.Manifest
		result2 error
	}
	getSnapshotManifestsReturnsOnCall map[int]struct {
		result1 []schema.Manifest
		result2 error
	}
	GetSnapshotSourceRegistryStub        func(*imagepromotera.Options) (*registry.Context, error)
	getSnapshotSourceRegistryMutex       sync.RWMutex
	getSnapshotSourceRegistryArgsForCall []struct {
		arg1 *imagepromotera.Options
	}
	getSnapshotSourceRegistryReturns struct {
		result1 *registry.Context
		result2 error
	}
	getSnapshotSourceRegistryReturnsOnCall map[int]struct {
		result1 *registry.Context
		result2 error
	}
	ParseManifestsStub        func(*imagepromotera.Options) ([]schema.Manifest, error)
	parseManifestsMutex       sync.RWMutex
	parseManifestsArgsForCall []struct {
		arg1 *imagepromotera.Options
	}
	parseManifestsReturns struct {
		result1 []schema.Manifest
		result2 error
	}
	parseManifestsReturnsOnCall map[int]struct {
		result1 []schema.Manifest
		result2 error
	}
	PrewarmTUFCacheStub        func() error
	prewarmTUFCacheMutex       sync.RWMutex
	prewarmTUFCacheArgsForCall []struct {
	}
	prewarmTUFCacheReturns struct {
		result1 error
	}
	prewarmTUFCacheReturnsOnCall map[int]struct {
		result1 error
	}
	PrintSecDisclaimerStub        func()
	printSecDisclaimerMutex       sync.RWMutex
	printSecDisclaimerArgsForCall []struct {
	}
	PrintVersionStub        func()
	printVersionMutex       sync.RWMutex
	printVersionArgsForCall []struct {
	}
	PromoteImagesStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	promoteImagesMutex       sync.RWMutex
	promoteImagesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}
	promoteImagesReturns struct {
		result1 error
	}
	promoteImagesReturnsOnCall map[int]struct {
		result1 error
	}
	ReplicateSignaturesStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	replicateSignaturesMutex       sync.RWMutex
	replicateSignaturesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}
	replicateSignaturesReturns struct {
		result1 error
	}
	replicateSignaturesReturnsOnCall map[int]struct {
		result1 error
	}
	ScanEdgesStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	scanEdgesMutex       sync.RWMutex
	scanEdgesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}
	scanEdgesReturns struct {
		result1 error
	}
	scanEdgesReturnsOnCall map[int]struct {
		result1 error
	}
	SignImagesStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	signImagesMutex       sync.RWMutex
	signImagesArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}
	signImagesReturns struct {
		result1 error
	}
	signImagesReturnsOnCall map[int]struct {
		result1 error
	}
	SnapshotStub        func(*imagepromotera.Options, registry.RegInvImage) error
	snapshotMutex       sync.RWMutex
	snapshotArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 registry.RegInvImage
	}
	snapshotReturns struct {
		result1 error
	}
	snapshotReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOptionsStub        func(*imagepromotera.Options) error
	validateOptionsMutex       sync.RWMutex
	validateOptionsArgsForCall []struct {
		arg1 *imagepromotera.Options
	}
	validateOptionsReturns struct {
		result1 error
	}
	validateOptionsReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateStagingSignaturesStub        func(map[promotion.Edge]any) (map[promotion.Edge]any, error)
	validateStagingSignaturesMutex       sync.RWMutex
	validateStagingSignaturesArgsForCall []struct {
		arg1 map[promotion.Edge]any
	}
	validateStagingSignaturesReturns struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	validateStagingSignaturesReturnsOnCall map[int]struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	WriteProvenanceAttestationsStub        func(*imagepromotera.Options, map[promotion.Edge]any, provenance.Generator) error
	writeProvenanceAttestationsMutex       sync.RWMutex
	writeProvenanceAttestationsArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
		arg3 provenance.Generator
	}
	writeProvenanceAttestationsReturns struct {
		result1 error
	}
	writeProvenanceAttestationsReturnsOnCall map[int]struct {
		result1 error
	}
	WriteSBOMsStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	writeSBOMsMutex       sync.RWMutex
	writeSBOMsArgsForCall []struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}
	writeSBOMsReturns struct {
		result1 error
	}
	writeSBOMsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePromoterImplementation) ActivateServiceAccounts(arg1 *imagepromotera.Options) error {
	fake.activateServiceAccountsMutex.Lock()
	ret, specificReturn := fake.activateServiceAccountsReturnsOnCall[len(fake.activateServiceAccountsArgsForCall)]
	fake.activateServiceAccountsArgsForCall = append(fake.activateServiceAccountsArgsForCall, struct {
		arg1 *imagepromotera.Options
	}{arg1})
	stub := fake.ActivateServiceAccountsStub
	fakeReturns := fake.activateServiceAccountsReturns
	fake.recordInvocation("ActivateServiceAccounts", []interface{}{arg1})
	fake.activateServiceAccountsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) ActivateServiceAccountsCallCount() int {
	fake.activateServiceAccountsMutex.RLock()
	defer fake.activateServiceAccountsMutex.RUnlock()
	return len(fake.activateServiceAccountsArgsForCall)
}

func (fake *FakePromoterImplementation) ActivateServiceAccountsCalls(stub func(*imagepromotera.Options) error) {
	fake.activateServiceAccountsMutex.Lock()
	defer fake.activateServiceAccountsMutex.Unlock()
	fake.ActivateServiceAccountsStub = stub
}

func (fake *FakePromoterImplementation) ActivateServiceAccountsArgsForCall(i int) *imagepromotera.Options {
	fake.activateServiceAccountsMutex.RLock()
	defer fake.activateServiceAccountsMutex.RUnlock()
	argsForCall := fake.activateServiceAccountsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) ActivateServiceAccountsReturns(result1 error) {
	fake.activateServiceAccountsMutex.Lock()
	defer fake.activateServiceAccountsMutex.Unlock()
	fake.ActivateServiceAccountsStub = nil
	fake.activateServiceAccountsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ActivateServiceAccountsReturnsOnCall(i int, result1 error) {
	fake.activateServiceAccountsMutex.Lock()
	defer fake.activateServiceAccountsMutex.Unlock()
	fake.ActivateServiceAccountsStub = nil
	if fake.activateServiceAccountsReturnsOnCall == nil {
		fake.activateServiceAccountsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.activateServiceAccountsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshot(arg1 *imagepromotera.Options, arg2 []schema.Manifest) ([]schema.Manifest, error) {
	var arg2Copy []schema.Manifest
	if arg2 != nil {
		arg2Copy = make([]schema.Manifest, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.appendManifestToSnapshotMutex.Lock()
	ret, specificReturn := fake.appendManifestToSnapshotReturnsOnCall[len(fake.appendManifestToSnapshotArgsForCall)]
	fake.appendManifestToSnapshotArgsForCall = append(fake.appendManifestToSnapshotArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 []schema.Manifest
	}{arg1, arg2Copy})
	stub := fake.AppendManifestToSnapshotStub
	fakeReturns := fake.appendManifestToSnapshotReturns
	fake.recordInvocation("AppendManifestToSnapshot", []interface{}{arg1, arg2Copy})
	fake.appendManifestToSnapshotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotCallCount() int {
	fake.appendManifestToSnapshotMutex.RLock()
	defer fake.appendManifestToSnapshotMutex.RUnlock()
	return len(fake.appendManifestToSnapshotArgsForCall)
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotCalls(stub func(*imagepromotera.Options, []schema.Manifest) ([]schema.Manifest, error)) {
	fake.appendManifestToSnapshotMutex.Lock()
	defer fake.appendManifestToSnapshotMutex.Unlock()
	fake.AppendManifestToSnapshotStub = stub
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotArgsForCall(i int) (*imagepromotera.Options, []schema.Manifest) {
	fake.appendManifestToSnapshotMutex.RLock()
	defer fake.appendManifestToSnapshotMutex.RUnlock()
	argsForCall := fake.appendManifestToSnapshotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotReturns(result1 []schema.Manifest, result2 error) {
	fake.appendManifestToSnapshotMutex.Lock()
	defer fake.appendManifestToSnapshotMutex.Unlock()
	fake.AppendManifestToSnapshotStub = nil
	fake.appendManifestToSnapshotReturns = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotReturnsOnCall(i int, result1 []schema.Manifest, result2 error) {
	fake.appendManifestToSnapshotMutex.Lock()
	defer fake.appendManifestToSnapshotMutex.Unlock()
	fake.AppendManifestToSnapshotStub = nil
	if fake.appendManifestToSnapshotReturnsOnCall == nil {
		fake.appendManifestToSnapshotReturnsOnCall = make(map[int]struct {
			result1 []schema.Manifest
			result2 error
		})
	}
	fake.appendManifestToSnapshotReturnsOnCall[i] = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) CopyFreshSignatures(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.copyFreshSignaturesMutex.Lock()
	ret, specificReturn := fake.copyFreshSignaturesReturnsOnCall[len(fake.copyFreshSignaturesArgsForCall)]
	fake.copyFreshSignaturesArgsForCall = append(fake.copyFreshSignaturesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}{arg1, arg2})
	stub := fake.CopyFreshSignaturesStub
	fakeReturns := fake.copyFreshSignaturesReturns
	fake.recordInvocation("CopyFreshSignatures", []interface{}{arg1, arg2})
	fake.copyFreshSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) CopyFreshSignaturesCallCount() int {
	fake.copyFreshSignaturesMutex.RLock()
	defer fake.copyFreshSignaturesMutex.RUnlock()
	return len(fake.copyFreshSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) CopyFreshSignaturesCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.copyFreshSignaturesMutex.Lock()
	defer fake.copyFreshSignaturesMutex.Unlock()
	fake.CopyFreshSignaturesStub = stub
}

func (fake *FakePromoterImplementation) CopyFreshSignaturesArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.copyFreshSignaturesMutex.RLock()
	defer fake.copyFreshSignaturesMutex.RUnlock()
	argsForCall := fake.copyFreshSignaturesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) CopyFreshSignaturesReturns(result1 error) {
	fake.copyFreshSignaturesMutex.Lock()
	defer fake.copyFreshSignaturesMutex.Unlock()
	fake.CopyFreshSignaturesStub = nil
	fake.copyFreshSignaturesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) CopyFreshSignaturesReturnsOnCall(i int, result1 error) {
	fake.copyFreshSignaturesMutex.Lock()
	defer fake.copyFreshSignaturesMutex.Unlock()
	fake.CopyFreshSignaturesStub = nil
	if fake.copyFreshSignaturesReturnsOnCall == nil {
		fake.copyFreshSignaturesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.copyFreshSignaturesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) EdgesFromManifests(arg1 []schema.Manifest) (map[promotion.Edge]any, error) {
	var arg1Copy []schema.Manifest
	if arg1 != nil {
		arg1Copy = make([]schema.Manifest, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.edgesFromManifestsMutex.Lock()
	ret, specificReturn := fake.edgesFromManifestsReturnsOnCall[len(fake.edgesFromManifestsArgsForCall)]
	fake.edgesFromManifestsArgsForCall = append(fake.edgesFromManifestsArgsForCall, struct {
		arg1 []schema.Manifest
	}{arg1Copy})
	stub := fake.EdgesFromManifestsStub
	fakeReturns := fake.edgesFromManifestsReturns
	fake.recordInvocation("EdgesFromManifests", []interface{}{arg1Copy})
	fake.edgesFromManifestsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) EdgesFromManifestsCallCount() int {
	fake.edgesFromManifestsMutex.RLock()
	defer fake.edgesFromManifestsMutex.RUnlock()
	return len(fake.edgesFromManifestsArgsForCall)
}

func (fake *FakePromoterImplementation) EdgesFromManifestsCalls(stub func([]schema.Manifest) (map[promotion.Edge]any, error)) {
	fake.edgesFromManifestsMutex.Lock()
	defer fake.edgesFromManifestsMutex.Unlock()
	fake.EdgesFromManifestsStub = stub
}

func (fake *FakePromoterImplementation) EdgesFromManifestsArgsForCall(i int) []schema.Manifest {
	fake.edgesFromManifestsMutex.RLock()
	defer fake.edgesFromManifestsMutex.RUnlock()
	argsForCall := fake.edgesFromManifestsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) EdgesFromManifestsReturns(result1 map[promotion.Edge]any, result2 error) {
	fake.edgesFromManifestsMutex.Lock()
	defer fake.edgesFromManifestsMutex.Unlock()
	fake.EdgesFromManifestsStub = nil
	fake.edgesFromManifestsReturns = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) EdgesFromManifestsReturnsOnCall(i int, result1 map[promotion.Edge]any, result2 error) {
	fake.edgesFromManifestsMutex.Lock()
	defer fake.edgesFromManifestsMutex.Unlock()
	fake.EdgesFromManifestsStub = nil
	if fake.edgesFromManifestsReturnsOnCall == nil {
		fake.edgesFromManifestsReturnsOnCall = make(map[int]struct {
			result1 map[promotion.Edge]any
			result2 error
		})
	}
	fake.edgesFromManifestsReturnsOnCall[i] = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) FixMissingSignatures(arg1 *imagepromotera.Options, arg2 checkresults.Signature) error {
	fake.fixMissingSignaturesMutex.Lock()
	ret, specificReturn := fake.fixMissingSignaturesReturnsOnCall[len(fake.fixMissingSignaturesArgsForCall)]
	fake.fixMissingSignaturesArgsForCall = append(fake.fixMissingSignaturesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 checkresults.Signature
	}{arg1, arg2})
	stub := fake.FixMissingSignaturesStub
	fakeReturns := fake.fixMissingSignaturesReturns
	fake.recordInvocation("FixMissingSignatures", []interface{}{arg1, arg2})
	fake.fixMissingSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) FixMissingSignaturesCallCount() int {
	fake.fixMissingSignaturesMutex.RLock()
	defer fake.fixMissingSignaturesMutex.RUnlock()
	return len(fake.fixMissingSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) FixMissingSignaturesCalls(stub func(*imagepromotera.Options, checkresults.Signature) error) {
	fake.fixMissingSignaturesMutex.Lock()
	defer fake.fixMissingSignaturesMutex.Unlock()
	fake.FixMissingSignaturesStub = stub
}

func (fake *FakePromoterImplementation) FixMissingSignaturesArgsForCall(i int) (*imagepromotera.Options, checkresults.Signature) {
	fake.fixMissingSignaturesMutex.RLock()
	defer fake.fixMissingSignaturesMutex.RUnlock()
	argsForCall := fake.fixMissingSignaturesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) FixMissingSignaturesReturns(result1 error) {
	fake.fixMissingSignaturesMutex.Lock()
	defer fake.fixMissingSignaturesMutex.Unlock()
	fake.FixMissingSignaturesStub = nil
	fake.fixMissingSignaturesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixMissingSignaturesReturnsOnCall(i int, result1 error) {
	fake.fixMissingSignaturesMutex.Lock()
	defer fake.fixMissingSignaturesMutex.Unlock()
	fake.FixMissingSignaturesStub = nil
	if fake.fixMissingSignaturesReturnsOnCall == nil {
		fake.fixMissingSignaturesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fixMissingSignaturesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixPartialSignatures(arg1 *imagepromotera.Options, arg2 checkresults.Signature) error {
	fake.fixPartialSignaturesMutex.Lock()
	ret, specificReturn := fake.fixPartialSignaturesReturnsOnCall[len(fake.fixPartialSignaturesArgsForCall)]
	fake.fixPartialSignaturesArgsForCall = append(fake.fixPartialSignaturesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 checkresults.Signature
	}{arg1, arg2})
	stub := fake.FixPartialSignaturesStub
	fakeReturns := fake.fixPartialSignaturesReturns
	fake.recordInvocation("FixPartialSignatures", []interface{}{arg1, arg2})
	fake.fixPartialSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) FixPartialSignaturesCallCount() int {
	fake.fixPartialSignaturesMutex.RLock()
	defer fake.fixPartialSignaturesMutex.RUnlock()
	return len(fake.fixPartialSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) FixPartialSignaturesCalls(stub func(*imagepromotera.Options, checkresults.Signature) error) {
	fake.fixPartialSignaturesMutex.Lock()
	defer fake.fixPartialSignaturesMutex.Unlock()
	fake.FixPartialSignaturesStub = stub
}

func (fake *FakePromoterImplementation) FixPartialSignaturesArgsForCall(i int) (*imagepromotera.Options, checkresults.Signature) {
	fake.fixPartialSignaturesMutex.RLock()
	defer fake.fixPartialSignaturesMutex.RUnlock()
	argsForCall := fake.fixPartialSignaturesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) FixPartialSignaturesReturns(result1 error) {
	fake.fixPartialSignaturesMutex.Lock()
	defer fake.fixPartialSignaturesMutex.Unlock()
	fake.FixPartialSignaturesStub = nil
	fake.fixPartialSignaturesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixPartialSignaturesReturnsOnCall(i int, result1 error) {
	fake.fixPartialSignaturesMutex.Lock()
	defer fake.fixPartialSignaturesMutex.Unlock()
	fake.FixPartialSignaturesStub = nil
	if fake.fixPartialSignaturesReturnsOnCall == nil {
		fake.fixPartialSignaturesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fixPartialSignaturesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) GetLatestImages(arg1 *imagepromotera.Options) ([]string, error) {
	fake.getLatestImagesMutex.Lock()
	ret, specificReturn := fake.getLatestImagesReturnsOnCall[len(fake.getLatestImagesArgsForCall)]
	fake.getLatestImagesArgsForCall = append(fake.getLatestImagesArgsForCall, struct {
		arg1 *imagepromotera.Options
	}{arg1})
	stub := fake.GetLatestImagesStub
	fakeReturns := fake.getLatestImagesReturns
	fake.recordInvocation("GetLatestImages", []interface{}{arg1})
	fake.getLatestImagesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetLatestImagesCallCount() int {
	fake.getLatestImagesMutex.RLock()
	defer fake.getLatestImagesMutex.RUnlock()
	return len(fake.getLatestImagesArgsForCall)
}

func (fake *FakePromoterImplementation) GetLatestImagesCalls(stub func(*imagepromotera.Options) ([]string, error)) {
	fake.getLatestImagesMutex.Lock()
	defer fake.getLatestImagesMutex.Unlock()
	fake.GetLatestImagesStub = stub
}

func (fake *FakePromoterImplementation) GetLatestImagesArgsForCall(i int) *imagepromotera.Options {
	fake.getLatestImagesMutex.RLock()
	defer fake.getLatestImagesMutex.RUnlock()
	argsForCall := fake.getLatestImagesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) GetLatestImagesReturns(result1 []string, result2 error) {
	fake.getLatestImagesMutex.Lock()
	defer fake.getLatestImagesMutex.Unlock()
	fake.GetLatestImagesStub = nil
	fake.getLatestImagesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetLatestImagesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getLatestImagesMutex.Lock()
	defer fake.getLatestImagesMutex.Unlock()
	fake.GetLatestImagesStub = nil
	if fake.getLatestImagesReturnsOnCall == nil {
		fake.getLatestImagesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getLatestImagesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetPromotionEdges(arg1 *imagepromotera.Options, arg2 []schema.Manifest) (map[promotion.Edge]any, error) {
	var arg2Copy []schema.Manifest
	if arg2 != nil {
		arg2Copy = make([]schema.Manifest, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getPromotionEdgesMutex.Lock()
	ret, specificReturn := fake.getPromotionEdgesReturnsOnCall[len(fake.getPromotionEdgesArgsForCall)]
	fake.getPromotionEdgesArgsForCall = append(fake.getPromotionEdgesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 []schema.Manifest
	}{arg1, arg2Copy})
	stub := fake.GetPromotionEdgesStub
	fakeReturns := fake.getPromotionEdgesReturns
	fake.recordInvocation("GetPromotionEdges", []interface{}{arg1, arg2Copy})
	fake.getPromotionEdgesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetPromotionEdgesCallCount() int {
	fake.getPromotionEdgesMutex.RLock()
	defer fake.getPromotionEdgesMutex.RUnlock()
	return len(fake.getPromotionEdgesArgsForCall)
}

func (fake *FakePromoterImplementation) GetPromotionEdgesCalls(stub func(*imagepromotera.Options, []schema.Manifest) (map[promotion.Edge]any, error)) {
	fake.getPromotionEdgesMutex.Lock()
	defer fake.getPromotionEdgesMutex.Unlock()
	fake.GetPromotionEdgesStub = stub
}

func (fake *FakePromoterImplementation) GetPromotionEdgesArgsForCall(i int) (*imagepromotera.Options, []schema.Manifest) {
	fake.getPromotionEdgesMutex.RLock()
	defer fake.getPromotionEdgesMutex.RUnlock()
	argsForCall := fake.getPromotionEdgesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) GetPromotionEdgesReturns(result1 map[promotion.Edge]any, result2 error) {
	fake.getPromotionEdgesMutex.Lock()
	defer fake.getPromotionEdgesMutex.Unlock()
	fake.GetPromotionEdgesStub = nil
	fake.getPromotionEdgesReturns = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetPromotionEdgesReturnsOnCall(i int, result1 map[promotion.Edge]any, result2 error) {
	fake.getPromotionEdgesMutex.Lock()
	defer fake.getPromotionEdgesMutex.Unlock()
	fake.GetPromotionEdgesStub = nil
	if fake.getPromotionEdgesReturnsOnCall == nil {
		fake.getPromotionEdgesReturnsOnCall = make(map[int]struct {
			result1 map[promotion.Edge]any
			result2 error
		})
	}
	fake.getPromotionEdgesReturnsOnCall[i] = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetRegistryImageInventory(arg1 *imagepromotera.Options, arg2 []schema.Manifest) (registry.RegInvImage, error) {
	var arg2Copy []schema.Manifest
	if arg2 != nil {
		arg2Copy = make([]schema.Manifest, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getRegistryImageInventoryMutex.Lock()
	ret, specificReturn := fake.getRegistryImageInventoryReturnsOnCall[len(fake.getRegistryImageInventoryArgsForCall)]
	fake.getRegistryImageInventoryArgsForCall = append(fake.getRegistryImageInventoryArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 []schema.Manifest
	}{arg1, arg2Copy})
	stub := fake.GetRegistryImageInventoryStub
	fakeReturns := fake.getRegistryImageInventoryReturns
	fake.recordInvocation("GetRegistryImageInventory", []interface{}{arg1, arg2Copy})
	fake.getRegistryImageInventoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryCallCount() int {
	fake.getRegistryImageInventoryMutex.RLock()
	defer fake.getRegistryImageInventoryMutex.RUnlock()
	return len(fake.getRegistryImageInventoryArgsForCall)
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryCalls(stub func(*imagepromotera.Options, []schema.Manifest) (registry.RegInvImage, error)) {
	fake.getRegistryImageInventoryMutex.Lock()
	defer fake.getRegistryImageInventoryMutex.Unlock()
	fake.GetRegistryImageInventoryStub = stub
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryArgsForCall(i int) (*imagepromotera.Options, []schema.Manifest) {
	fake.getRegistryImageInventoryMutex.RLock()
	defer fake.getRegistryImageInventoryMutex.RUnlock()
	argsForCall := fake.getRegistryImageInventoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryReturns(result1 registry.RegInvImage, result2 error) {
	fake.getRegistryImageInventoryMutex.Lock()
	defer fake.getRegistryImageInventoryMutex.Unlock()
	fake.GetRegistryImageInventoryStub = nil
	fake.getRegistryImageInventoryReturns = struct {
		result1 registry.RegInvImage
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryReturnsOnCall(i int, result1 registry.RegInvImage, result2 error) {
	fake.getRegistryImageInventoryMutex.Lock()
	defer fake.getRegistryImageInventoryMutex.Unlock()
	fake.GetRegistryImageInventoryStub = nil
	if fake.getRegistryImageInventoryReturnsOnCall == nil {
		fake.getRegistryImageInventoryReturnsOnCall = make(map[int]struct {
			result1 registry.RegInvImage
			result2 error
		})
	}
	fake.getRegistryImageInventoryReturnsOnCall[i] = struct {
		result1 registry.RegInvImage
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSignatureStatus(arg1 *imagepromotera.Options, arg2 []string) (checkresults.Signature, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getSignatureStatusMutex.Lock()
	ret, specificReturn := fake.getSignatureStatusReturnsOnCall[len(fake.getSignatureStatusArgsForCall)]
	fake.getSignatureStatusArgsForCall = append(fake.getSignatureStatusArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.GetSignatureStatusStub
	fakeReturns := fake.getSignatureStatusReturns
	fake.recordInvocation("GetSignatureStatus", []interface{}{arg1, arg2Copy})
	fake.getSignatureStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetSignatureStatusCallCount() int {
	fake.getSignatureStatusMutex.RLock()
	defer fake.getSignatureStatusMutex.RUnlock()
	return len(fake.getSignatureStatusArgsForCall)
}

func (fake *FakePromoterImplementation) GetSignatureStatusCalls(stub func(*imagepromotera.Options, []string) (checkresults.Signature, error)) {
	fake.getSignatureStatusMutex.Lock()
	defer fake.getSignatureStatusMutex.Unlock()
	fake.GetSignatureStatusStub = stub
}

func (fake *FakePromoterImplementation) GetSignatureStatusArgsForCall(i int) (*imagepromotera.Options, []string) {
	fake.getSignatureStatusMutex.RLock()
	defer fake.getSignatureStatusMutex.RUnlock()
	argsForCall := fake.getSignatureStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) GetSignatureStatusReturns(result1 checkresults.Signature, result2 error) {
	fake.getSignatureStatusMutex.Lock()
	defer fake.getSignatureStatusMutex.Unlock()
	fake.GetSignatureStatusStub = nil
	fake.getSignatureStatusReturns = struct {
		result1 checkresults.Signature
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSignatureStatusReturnsOnCall(i int, result1 checkresults.Signature, result2 error) {
	fake.getSignatureStatusMutex.Lock()
	defer fake.getSignatureStatusMutex.Unlock()
	fake.GetSignatureStatusStub = nil
	if fake.getSignatureStatusReturnsOnCall == nil {
		fake.getSignatureStatusReturnsOnCall = make(map[int]struct {
			result1 checkresults.Signature
			result2 error
		})
	}
	fake.getSignatureStatusReturnsOnCall[i] = struct {
		result1 checkresults.Signature
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotManifests(arg1 *imagepromotera.Options) ([]schema.Manifest, error) {
	fake.getSnapshotManifestsMutex.Lock()
	ret, specificReturn := fake.getSnapshotManifestsReturnsOnCall[len(fake.getSnapshotManifestsArgsForCall)]
	fake.getSnapshotManifestsArgsForCall = append(fake.getSnapshotManifestsArgsForCall, struct {
		arg1 *imagepromotera.Options
	}{arg1})
	stub := fake.GetSnapshotManifestsStub
	fakeReturns := fake.getSnapshotManifestsReturns
	fake.recordInvocation("GetSnapshotManifests", []interface{}{arg1})
	fake.getSnapshotManifestsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsCallCount() int {
	fake.getSnapshotManifestsMutex.RLock()
	defer fake.getSnapshotManifestsMutex.RUnlock()
	return len(fake.getSnapshotManifestsArgsForCall)
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsCalls(stub func(*imagepromotera.Options) ([]schema.Manifest, error)) {
	fake.getSnapshotManifestsMutex.Lock()
	defer fake.getSnapshotManifestsMutex.Unlock()
	fake.GetSnapshotManifestsStub = stub
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsArgsForCall(i int) *imagepromotera.Options {
	fake.getSnapshotManifestsMutex.RLock()
	defer fake.getSnapshotManifestsMutex.RUnlock()
	argsForCall := fake.getSnapshotManifestsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsReturns(result1 []schema.Manifest, result2 error) {
	fake.getSnapshotManifestsMutex.Lock()
	defer fake.getSnapshotManifestsMutex.Unlock()
	fake.GetSnapshotManifestsStub = nil
	fake.getSnapshotManifestsReturns = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsReturnsOnCall(i int, result1 []schema.Manifest, result2 error) {
	fake.getSnapshotManifestsMutex.Lock()
	defer fake.getSnapshotManifestsMutex.Unlock()
	fake.GetSnapshotManifestsStub = nil
	if fake.getSnapshotManifestsReturnsOnCall == nil {
		fake.getSnapshotManifestsReturnsOnCall = make(map[int]struct {
			result1 []schema.Manifest
			result2 error
		})
	}
	fake.getSnapshotManifestsReturnsOnCall[i] = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistry(arg1 *imagepromotera.Options) (*registry.Context, error) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	ret, specificReturn := fake.getSnapshotSourceRegistryReturnsOnCall[len(fake.getSnapshotSourceRegistryArgsForCall)]
	fake.getSnapshotSourceRegistryArgsForCall = append(fake.getSnapshotSourceRegistryArgsForCall, struct {
		arg1 *imagepromotera.Options
	}{arg1})
	stub := fake.GetSnapshotSourceRegistryStub
	fakeReturns := fake.getSnapshotSourceRegistryReturns
	fake.recordInvocation("GetSnapshotSourceRegistry", []interface{}{arg1})
	fake.getSnapshotSourceRegistryMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryCallCount() int {
	fake.getSnapshotSourceRegistryMutex.RLock()
	defer fake.getSnapshotSourceRegistryMutex.RUnlock()
	return len(fake.getSnapshotSourceRegistryArgsForCall)
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryCalls(stub func(*imagepromotera.Options) (*registry.Context, error)) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	defer fake.getSnapshotSourceRegistryMutex.Unlock()
	fake.GetSnapshotSourceRegistryStub = stub
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryArgsForCall(i int) *imagepromotera.Options {
	fake.getSnapshotSourceRegistryMutex.RLock()
	defer fake.getSnapshotSourceRegistryMutex.RUnlock()
	argsForCall := fake.getSnapshotSourceRegistryArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryReturns(result1 *registry.Context, result2 error) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	defer fake.getSnapshotSourceRegistryMutex.Unlock()
	fake.GetSnapshotSourceRegistryStub = nil
	fake.getSnapshotSourceRegistryReturns = struct {
		result1 *registry.Context
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryReturnsOnCall(i int, result1 *registry.Context, result2 error) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	defer fake.getSnapshotSourceRegistryMutex.Unlock()
	fake.GetSnapshotSourceRegistryStub = nil
	if fake.getSnapshotSourceRegistryReturnsOnCall == nil {
		fake.getSnapshotSourceRegistryReturnsOnCall = make(map[int]struct {
			result1 *registry.Context
			result2 error
		})
	}
	fake.getSnapshotSourceRegistryReturnsOnCall[i] = struct {
		result1 *registry.Context
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) ParseManifests(arg1 *imagepromotera.Options) ([]schema.Manifest, error) {
	fake.parseManifestsMutex.Lock()
	ret, specificReturn := fake.parseManifestsReturnsOnCall[len(fake.parseManifestsArgsForCall)]
	fake.parseManifestsArgsForCall = append(fake.parseManifestsArgsForCall, struct {
		arg1 *imagepromotera.Options
	}{arg1})
	stub := fake.ParseManifestsStub
	fakeReturns := fake.parseManifestsReturns
	fake.recordInvocation("ParseManifests", []interface{}{arg1})
	fake.parseManifestsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) ParseManifestsCallCount() int {
	fake.parseManifestsMutex.RLock()
	defer fake.parseManifestsMutex.RUnlock()
	return len(fake.parseManifestsArgsForCall)
}

func (fake *FakePromoterImplementation) ParseManifestsCalls(stub func(*imagepromotera.Options) ([]schema.Manifest, error)) {
	fake.parseManifestsMutex.Lock()
	defer fake.parseManifestsMutex.Unlock()
	fake.ParseManifestsStub = stub
}

func (fake *FakePromoterImplementation) ParseManifestsArgsForCall(i int) *imagepromotera.Options {
	fake.parseManifestsMutex.RLock()
	defer fake.parseManifestsMutex.RUnlock()
	argsForCall := fake.parseManifestsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) ParseManifestsReturns(result1 []schema.Manifest, result2 error) {
	fake.parseManifestsMutex.Lock()
	defer fake.parseManifestsMutex.Unlock()
	fake.ParseManifestsStub = nil
	fake.parseManifestsReturns = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) ParseManifestsReturnsOnCall(i int, result1 []schema.Manifest, result2 error) {
	fake.parseManifestsMutex.Lock()
	defer fake.parseManifestsMutex.Unlock()
	fake.ParseManifestsStub = nil
	if fake.parseManifestsReturnsOnCall == nil {
		fake.parseManifestsReturnsOnCall = make(map[int]struct {
			result1 []schema.Manifest
			result2 error
		})
	}
	fake.parseManifestsReturnsOnCall[i] = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) PrewarmTUFCache() error {
	fake.prewarmTUFCacheMutex.Lock()
	ret, specificReturn := fake.prewarmTUFCacheReturnsOnCall[len(fake.prewarmTUFCacheArgsForCall)]
	fake.prewarmTUFCacheArgsForCall = append(fake.prewarmTUFCacheArgsForCall, struct {
	}{})
	stub := fake.PrewarmTUFCacheStub
	fakeReturns := fake.prewarmTUFCacheReturns
	fake.recordInvocation("PrewarmTUFCache", []interface{}{})
	fake.prewarmTUFCacheMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheCallCount() int {
	fake.prewarmTUFCacheMutex.RLock()
	defer fake.prewarmTUFCacheMutex.RUnlock()
	return len(fake.prewarmTUFCacheArgsForCall)
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheCalls(stub func() error) {
	fake.prewarmTUFCacheMutex.Lock()
	defer fake.prewarmTUFCacheMutex.Unlock()
	fake.PrewarmTUFCacheStub = stub
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheReturns(result1 error) {
	fake.prewarmTUFCacheMutex.Lock()
	defer fake.prewarmTUFCacheMutex.Unlock()
	fake.PrewarmTUFCacheStub = nil
	fake.prewarmTUFCacheReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheReturnsOnCall(i int, result1 error) {
	fake.prewarmTUFCacheMutex.Lock()
	defer fake.prewarmTUFCacheMutex.Unlock()
	fake.PrewarmTUFCacheStub = nil
	if fake.prewarmTUFCacheReturnsOnCall == nil {
		fake.prewarmTUFCacheReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.prewarmTUFCacheReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) PrintSecDisclaimer() {
	fake.printSecDisclaimerMutex.Lock()
	fake.printSecDisclaimerArgsForCall = append(fake.printSecDisclaimerArgsForCall, struct {
	}{})
	stub := fake.PrintSecDisclaimerStub
	fake.recordInvocation("PrintSecDisclaimer", []interface{}{})
	fake.printSecDisclaimerMutex.Unlock()
	if stub != nil {
		fake.PrintSecDisclaimerStub()
	}
}

func (fake *FakePromoterImplementation) PrintSecDisclaimerCallCount() int {
	fake.printSecDisclaimerMutex.RLock()
	defer fake.printSecDisclaimerMutex.RUnlock()
	return len(fake.printSecDisclaimerArgsForCall)
}

func (fake *FakePromoterImplementation) PrintSecDisclaimerCalls(stub func()) {
	fake.printSecDisclaimerMutex.Lock()
	defer fake.printSecDisclaimerMutex.Unlock()
	fake.PrintSecDisclaimerStub = stub
}

func (fake *FakePromoterImplementation) PrintVersion() {
	fake.printVersionMutex.Lock()
	fake.printVersionArgsForCall = append(fake.printVersionArgsForCall, struct {
	}{})
	stub := fake.PrintVersionStub
	fake.recordInvocation("PrintVersion", []interface{}{})
	fake.printVersionMutex.Unlock()
	if stub != nil {
		fake.PrintVersionStub()
	}
}

func (fake *FakePromoterImplementation) PrintVersionCallCount() int {
	fake.printVersionMutex.RLock()
	defer fake.printVersionMutex.RUnlock()
	return len(fake.printVersionArgsForCall)
}

func (fake *FakePromoterImplementation) PrintVersionCalls(stub func()) {
	fake.printVersionMutex.Lock()
	defer fake.printVersionMutex.Unlock()
	fake.PrintVersionStub = stub
}

func (fake *FakePromoterImplementation) PromoteImages(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.promoteImagesMutex.Lock()
	ret, specificReturn := fake.promoteImagesReturnsOnCall[len(fake.promoteImagesArgsForCall)]
	fake.promoteImagesArgsForCall = append(fake.promoteImagesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}{arg1, arg2})
	stub := fake.PromoteImagesStub
	fakeReturns := fake.promoteImagesReturns
	fake.recordInvocation("PromoteImages", []interface{}{arg1, arg2})
	fake.promoteImagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) PromoteImagesCallCount() int {
	fake.promoteImagesMutex.RLock()
	defer fake.promoteImagesMutex.RUnlock()
	return len(fake.promoteImagesArgsForCall)
}

func (fake *FakePromoterImplementation) PromoteImagesCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.promoteImagesMutex.Lock()
	defer fake.promoteImagesMutex.Unlock()
	fake.PromoteImagesStub = stub
}

func (fake *FakePromoterImplementation) PromoteImagesArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.promoteImagesMutex.RLock()
	defer fake.promoteImagesMutex.RUnlock()
	argsForCall := fake.promoteImagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) PromoteImagesReturns(result1 error) {
	fake.promoteImagesMutex.Lock()
	defer fake.promoteImagesMutex.Unlock()
	fake.PromoteImagesStub = nil
	fake.promoteImagesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) PromoteImagesReturnsOnCall(i int, result1 error) {
	fake.promoteImagesMutex.Lock()
	defer fake.promoteImagesMutex.Unlock()
	fake.PromoteImagesStub = nil
	if fake.promoteImagesReturnsOnCall == nil {
		fake.promoteImagesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.promoteImagesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ReplicateSignatures(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.replicateSignaturesMutex.Lock()
	ret, specificReturn := fake.replicateSignaturesReturnsOnCall[len(fake.replicateSignaturesArgsForCall)]
	fake.replicateSignaturesArgsForCall = append(fake.replicateSignaturesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}{arg1, arg2})
	stub := fake.ReplicateSignaturesStub
	fakeReturns := fake.replicateSignaturesReturns
	fake.recordInvocation("ReplicateSignatures", []interface{}{arg1, arg2})
	fake.replicateSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) ReplicateSignaturesCallCount() int {
	fake.replicateSignaturesMutex.RLock()
	defer fake.replicateSignaturesMutex.RUnlock()
	return len(fake.replicateSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) ReplicateSignaturesCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.replicateSignaturesMutex.Lock()
	defer fake.replicateSignaturesMutex.Unlock()
	fake.ReplicateSignaturesStub = stub
}

func (fake *FakePromoterImplementation) ReplicateSignaturesArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.replicateSignaturesMutex.RLock()
	defer fake.replicateSignaturesMutex.RUnlock()
	argsForCall := fake.replicateSignaturesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) ReplicateSignaturesReturns(result1 error) {
	fake.replicateSignaturesMutex.Lock()
	defer fake.replicateSignaturesMutex.Unlock()
	fake.ReplicateSignaturesStub = nil
	fake.replicateSignaturesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ReplicateSignaturesReturnsOnCall(i int, result1 error) {
	fake.replicateSignaturesMutex.Lock()
	defer fake.replicateSignaturesMutex.Unlock()
	fake.ReplicateSignaturesStub = nil
	if fake.replicateSignaturesReturnsOnCall == nil {
		fake.replicateSignaturesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.replicateSignaturesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ScanEdges(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.scanEdgesMutex.Lock()
	ret, specificReturn := fake.scanEdgesReturnsOnCall[len(fake.scanEdgesArgsForCall)]
	fake.scanEdgesArgsForCall = append(fake.scanEdgesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}{arg1, arg2})
	stub := fake.ScanEdgesStub
	fakeReturns := fake.scanEdgesReturns
	fake.recordInvocation("ScanEdges", []interface{}{arg1, arg2})
	fake.scanEdgesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) ScanEdgesCallCount() int {
	fake.scanEdgesMutex.RLock()
	defer fake.scanEdgesMutex.RUnlock()
	return len(fake.scanEdgesArgsForCall)
}

func (fake *FakePromoterImplementation) ScanEdgesCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.scanEdgesMutex.Lock()
	defer fake.scanEdgesMutex.Unlock()
	fake.ScanEdgesStub = stub
}

func (fake *FakePromoterImplementation) ScanEdgesArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.scanEdgesMutex.RLock()
	defer fake.scanEdgesMutex.RUnlock()
	argsForCall := fake.scanEdgesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) ScanEdgesReturns(result1 error) {
	fake.scanEdgesMutex.Lock()
	defer fake.scanEdgesMutex.Unlock()
	fake.ScanEdgesStub = nil
	fake.scanEdgesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ScanEdgesReturnsOnCall(i int, result1 error) {
	fake.scanEdgesMutex.Lock()
	defer fake.scanEdgesMutex.Unlock()
	fake.ScanEdgesStub = nil
	if fake.scanEdgesReturnsOnCall == nil {
		fake.scanEdgesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.scanEdgesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) SignImages(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.signImagesMutex.Lock()
	ret, specificReturn := fake.signImagesReturnsOnCall[len(fake.signImagesArgsForCall)]
	fake.signImagesArgsForCall = append(fake.signImagesArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}{arg1, arg2})
	stub := fake.SignImagesStub
	fakeReturns := fake.signImagesReturns
	fake.recordInvocation("SignImages", []interface{}{arg1, arg2})
	fake.signImagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) SignImagesCallCount() int {
	fake.signImagesMutex.RLock()
	defer fake.signImagesMutex.RUnlock()
	return len(fake.signImagesArgsForCall)
}

func (fake *FakePromoterImplementation) SignImagesCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.signImagesMutex.Lock()
	defer fake.signImagesMutex.Unlock()
	fake.SignImagesStub = stub
}

func (fake *FakePromoterImplementation) SignImagesArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.signImagesMutex.RLock()
	defer fake.signImagesMutex.RUnlock()
	argsForCall := fake.signImagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) SignImagesReturns(result1 error) {
	fake.signImagesMutex.Lock()
	defer fake.signImagesMutex.Unlock()
	fake.SignImagesStub = nil
	fake.signImagesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) SignImagesReturnsOnCall(i int, result1 error) {
	fake.signImagesMutex.Lock()
	defer fake.signImagesMutex.Unlock()
	fake.SignImagesStub = nil
	if fake.signImagesReturnsOnCall == nil {
		fake.signImagesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.signImagesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) Snapshot(arg1 *imagepromotera.Options, arg2 registry.RegInvImage) error {
	fake.snapshotMutex.Lock()
	ret, specificReturn := fake.snapshotReturnsOnCall[len(fake.snapshotArgsForCall)]
	fake.snapshotArgsForCall = append(fake.snapshotArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 registry.RegInvImage
	}{arg1, arg2})
	stub := fake.SnapshotStub
	fakeReturns := fake.snapshotReturns
	fake.recordInvocation("Snapshot", []interface{}{arg1, arg2})
	fake.snapshotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) SnapshotCallCount() int {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	return len(fake.snapshotArgsForCall)
}

func (fake *FakePromoterImplementation) SnapshotCalls(stub func(*imagepromotera.Options, registry.RegInvImage) error) {
	fake.snapshotMutex.Lock()
	defer fake.snapshotMutex.Unlock()
	fake.SnapshotStub = stub
}

func (fake *FakePromoterImplementation) SnapshotArgsForCall(i int) (*imagepromotera.Options, registry.RegInvImage) {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	argsForCall := fake.snapshotArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) SnapshotReturns(result1 error) {
	fake.snapshotMutex.Lock()
	defer fake.snapshotMutex.Unlock()
	fake.SnapshotStub = nil
	fake.snapshotReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) SnapshotReturnsOnCall(i int, result1 error) {
	fake.snapshotMutex.Lock()
	defer fake.snapshotMutex.Unlock()
	fake.SnapshotStub = nil
	if fake.snapshotReturnsOnCall == nil {
		fake.snapshotReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.snapshotReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ValidateOptions(arg1 *imagepromotera.Options) error {
	fake.validateOptionsMutex.Lock()
	ret, specificReturn := fake.validateOptionsReturnsOnCall[len(fake.validateOptionsArgsForCall)]
	fake.validateOptionsArgsForCall = append(fake.validateOptionsArgsForCall, struct {
		arg1 *imagepromotera.Options
	}{arg1})
	stub := fake.ValidateOptionsStub
	fakeReturns := fake.validateOptionsReturns
	fake.recordInvocation("ValidateOptions", []interface{}{arg1})
	fake.validateOptionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) ValidateOptionsCallCount() int {
	fake.validateOptionsMutex.RLock()
	defer fake.validateOptionsMutex.RUnlock()
	return len(fake.validateOptionsArgsForCall)
}

func (fake *FakePromoterImplementation) ValidateOptionsCalls(stub func(*imagepromotera.Options) error) {
	fake.validateOptionsMutex.Lock()
	defer fake.validateOptionsMutex.Unlock()
	fake.ValidateOptionsStub = stub
}

func (fake *FakePromoterImplementation) ValidateOptionsArgsForCall(i int) *imagepromotera.Options {
	fake.validateOptionsMutex.RLock()
	defer fake.validateOptionsMutex.RUnlock()
	argsForCall := fake.validateOptionsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) ValidateOptionsReturns(result1 error) {
	fake.validateOptionsMutex.Lock()
	defer fake.validateOptionsMutex.Unlock()
	fake.ValidateOptionsStub = nil
	fake.validateOptionsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ValidateOptionsReturnsOnCall(i int, result1 error) {
	fake.validateOptionsMutex.Lock()
	defer fake.validateOptionsMutex.Unlock()
	fake.ValidateOptionsStub = nil
	if fake.validateOptionsReturnsOnCall == nil {
		fake.validateOptionsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOptionsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ValidateStagingSignatures(arg1 map[promotion.Edge]any) (map[promotion.Edge]any, error) {
	fake.validateStagingSignaturesMutex.Lock()
	ret, specificReturn := fake.validateStagingSignaturesReturnsOnCall[len(fake.validateStagingSignaturesArgsForCall)]
	fake.validateStagingSignaturesArgsForCall = append(fake.validateStagingSignaturesArgsForCall, struct {
		arg1 map[promotion.Edge]any
	}{arg1})
	stub := fake.ValidateStagingSignaturesStub
	fakeReturns := fake.validateStagingSignaturesReturns
	fake.recordInvocation("ValidateStagingSignatures", []interface{}{arg1})
	fake.validateStagingSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesCallCount() int {
	fake.validateStagingSignaturesMutex.RLock()
	defer fake.validateStagingSignaturesMutex.RUnlock()
	return len(fake.validateStagingSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesCalls(stub func(map[promotion.Edge]any) (map[promotion.Edge]any, error)) {
	fake.validateStagingSignaturesMutex.Lock()
	defer fake.validateStagingSignaturesMutex.Unlock()
	fake.ValidateStagingSignaturesStub = stub
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesArgsForCall(i int) map[promotion.Edge]any {
	fake.validateStagingSignaturesMutex.RLock()
	defer fake.validateStagingSignaturesMutex.RUnlock()
	argsForCall := fake.validateStagingSignaturesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesReturns(result1 map[promotion.Edge]any, result2 error) {
	fake.validateStagingSignaturesMutex.Lock()
	defer fake.validateStagingSignaturesMutex.Unlock()
	fake.ValidateStagingSignaturesStub = nil
	fake.validateStagingSignaturesReturns = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesReturnsOnCall(i int, result1 map[promotion.Edge]any, result2 error) {
	fake.validateStagingSignaturesMutex.Lock()
	defer fake.validateStagingSignaturesMutex.Unlock()
	fake.ValidateStagingSignaturesStub = nil
	if fake.validateStagingSignaturesReturnsOnCall == nil {
		fake.validateStagingSignaturesReturnsOnCall = make(map[int]struct {
			result1 map[promotion.Edge]any
			result2 error
		})
	}
	fake.validateStagingSignaturesReturnsOnCall[i] = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestations(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any, arg3 provenance.Generator) error {
	fake.writeProvenanceAttestationsMutex.Lock()
	ret, specificReturn := fake.writeProvenanceAttestationsReturnsOnCall[len(fake.writeProvenanceAttestationsArgsForCall)]
	fake.writeProvenanceAttestationsArgsForCall = append(fake.writeProvenanceAttestationsArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
		arg3 provenance.Generator
	}{arg1, arg2, arg3})
	stub := fake.WriteProvenanceAttestationsStub
	fakeReturns := fake.writeProvenanceAttestationsReturns
	fake.recordInvocation("WriteProvenanceAttestations", []interface{}{arg1, arg2, arg3})
	fake.writeProvenanceAttestationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsCallCount() int {
	fake.writeProvenanceAttestationsMutex.RLock()
	defer fake.writeProvenanceAttestationsMutex.RUnlock()
	return len(fake.writeProvenanceAttestationsArgsForCall)
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any, provenance.Generator) error) {
	fake.writeProvenanceAttestationsMutex.Lock()
	defer fake.writeProvenanceAttestationsMutex.Unlock()
	fake.WriteProvenanceAttestationsStub = stub
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any, provenance.Generator) {
	fake.writeProvenanceAttestationsMutex.RLock()
	defer fake.writeProvenanceAttestationsMutex.RUnlock()
	argsForCall := fake.writeProvenanceAttestationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsReturns(result1 error) {
	fake.writeProvenanceAttestationsMutex.Lock()
	defer fake.writeProvenanceAttestationsMutex.Unlock()
	fake.WriteProvenanceAttestationsStub = nil
	fake.writeProvenanceAttestationsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsReturnsOnCall(i int, result1 error) {
	fake.writeProvenanceAttestationsMutex.Lock()
	defer fake.writeProvenanceAttestationsMutex.Unlock()
	fake.WriteProvenanceAttestationsStub = nil
	if fake.writeProvenanceAttestationsReturnsOnCall == nil {
		fake.writeProvenanceAttestationsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeProvenanceAttestationsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) WriteSBOMs(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.writeSBOMsMutex.Lock()
	ret, specificReturn := fake.writeSBOMsReturnsOnCall[len(fake.writeSBOMsArgsForCall)]
	fake.writeSBOMsArgsForCall = append(fake.writeSBOMsArgsForCall, struct {
		arg1 *imagepromotera.Options
		arg2 map[promotion.Edge]any
	}{arg1, arg2})
	stub := fake.WriteSBOMsStub
	fakeReturns := fake.writeSBOMsReturns
	fake.recordInvocation("WriteSBOMs", []interface{}{arg1, arg2})
	fake.writeSBOMsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) WriteSBOMsCallCount() int {
	fake.writeSBOMsMutex.RLock()
	defer fake.writeSBOMsMutex.RUnlock()
	return len(fake.writeSBOMsArgsForCall)
}

func (fake *FakePromoterImplementation) WriteSBOMsCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.writeSBOMsMutex.Lock()
	defer fake.writeSBOMsMutex.Unlock()
	fake.WriteSBOMsStub = stub
}

func (fake *FakePromoterImplementation) WriteSBOMsArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.writeSBOMsMutex.RLock()
	defer fake.writeSBOMsMutex.RUnlock()
	argsForCall := fake.writeSBOMsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePromoterImplementation) WriteSBOMsReturns(result1 error) {
	fake.writeSBOMsMutex.Lock()
	defer fake.writeSBOMsMutex.Unlock()
	fake.WriteSBOMsStub = nil
	fake.writeSBOMsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) WriteSBOMsReturnsOnCall(i int, result1 error) {
	fake.writeSBOMsMutex.Lock()
	defer fake.writeSBOMsMutex.Unlock()
	fake.WriteSBOMsStub = nil
	if fake.writeSBOMsReturnsOnCall == nil {
		fake.writeSBOMsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeSBOMsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePromoterImplementation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
