/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by counterfeiter. DO NOT EDIT.
package imagefakes

import (
	"context"
	"sync"

	"sigs.k8s.io/promo-tools/v4/promoter/image/checkresults"
	imagepromotera "sigs.k8s.io/promo-tools/v4/promoter/image/options"
	"sigs.k8s.io/promo-tools/v4/promoter/image/promotion"
	"sigs.k8s.io/promo-tools/v4/promoter/image/provenance"
	"sigs.k8s.io/promo-tools/v4/promoter/image/registry"
	"sigs.k8s.io/promo-tools/v4/promoter/image/schema"
)

type FakePromoterImplementation struct {
	AppendManifestToSnapshotStub        func(*imagepromotera.Options, []schema.Manifest) ([]schema.Manifest, error)
	appendManifestToSnapshotMutex       sync.RWMutex
	appendManifestToSnapshotArgsForCall []FakePromoterImplementationAppendManifestToSnapshotArgs
	appendManifestToSnapshotReturns     struct {
		result1 []schema.Manifest
		result2 error
	}
	appendManifestToSnapshotReturnsOnCall map[int]struct {
		result1 []schema.Manifest
		result2 error
	}
	CarryAttestationsStub        func(context.Context, *imagepromotera.Options, map[promotion.Edge]any, map[string]*provenance.ImageProvenance) error
	carryAttestationsMutex       sync.RWMutex
	carryAttestationsArgsForCall []FakePromoterImplementationCarryAttestationsArgs
	carryAttestationsReturns     struct {
		result1 error
	}
	carryAttestationsReturnsOnCall map[int]struct {
		result1 error
	}
	FixMissingAttestationsStub        func(context.Context, *imagepromotera.Options, checkresults.Results, provenance.Generator) error
	fixMissingAttestationsMutex       sync.RWMutex
	fixMissingAttestationsArgsForCall []FakePromoterImplementationFixMissingAttestationsArgs
	fixMissingAttestationsReturns     struct {
		result1 error
	}
	fixMissingAttestationsReturnsOnCall map[int]struct {
		result1 error
	}
	FixMissingSignaturesStub        func(context.Context, *imagepromotera.Options, checkresults.Results) error
	fixMissingSignaturesMutex       sync.RWMutex
	fixMissingSignaturesArgsForCall []FakePromoterImplementationFixMissingSignaturesArgs
	fixMissingSignaturesReturns     struct {
		result1 error
	}
	fixMissingSignaturesReturnsOnCall map[int]struct {
		result1 error
	}
	GetLatestImagesStub        func(context.Context, *imagepromotera.Options) ([]checkresults.Image, error)
	getLatestImagesMutex       sync.RWMutex
	getLatestImagesArgsForCall []FakePromoterImplementationGetLatestImagesArgs
	getLatestImagesReturns     struct {
		result1 []checkresults.Image
		result2 error
	}
	getLatestImagesReturnsOnCall map[int]struct {
		result1 []checkresults.Image
		result2 error
	}
	GetPromotionEdgesStub        func(context.Context, *imagepromotera.Options, []schema.Manifest) (map[promotion.Edge]any, error)
	getPromotionEdgesMutex       sync.RWMutex
	getPromotionEdgesArgsForCall []FakePromoterImplementationGetPromotionEdgesArgs
	getPromotionEdgesReturns     struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	getPromotionEdgesReturnsOnCall map[int]struct {
		result1 map[promotion.Edge]any
		result2 error
	}
	GetRegistryImageInventoryStub        func(context.Context, *imagepromotera.Options, []schema.Manifest) (registry.RegInvImage, error)
	getRegistryImageInventoryMutex       sync.RWMutex
	getRegistryImageInventoryArgsForCall []FakePromoterImplementationGetRegistryImageInventoryArgs
	getRegistryImageInventoryReturns     struct {
		result1 registry.RegInvImage
		result2 error
	}
	getRegistryImageInventoryReturnsOnCall map[int]struct {
		result1 registry.RegInvImage
		result2 error
	}
	GetSignatureStatusStub        func(context.Context, *imagepromotera.Options, []checkresults.Image) (checkresults.Results, error)
	getSignatureStatusMutex       sync.RWMutex
	getSignatureStatusArgsForCall []FakePromoterImplementationGetSignatureStatusArgs
	getSignatureStatusReturns     struct {
		result1 checkresults.Results
		result2 error
	}
	getSignatureStatusReturnsOnCall map[int]struct {
		result1 checkresults.Results
		result2 error
	}
	GetSnapshotManifestsStub        func(*imagepromotera.Options) ([]schema.Manifest, error)
	getSnapshotManifestsMutex       sync.RWMutex
	getSnapshotManifestsArgsForCall []FakePromoterImplementationGetSnapshotManifestsArgs
	getSnapshotManifestsReturns     struct {
		result1 []schema.Manifest
		result2 error
	}
	getSnapshotManifestsReturnsOnCall map[int]struct {
		result1 []schema.Manifest
		result2 error
	}
	GetSnapshotSourceRegistryStub        func(*imagepromotera.Options) (*registry.Context, error)
	getSnapshotSourceRegistryMutex       sync.RWMutex
	getSnapshotSourceRegistryArgsForCall []FakePromoterImplementationGetSnapshotSourceRegistryArgs
	getSnapshotSourceRegistryReturns     struct {
		result1 *registry.Context
		result2 error
	}
	getSnapshotSourceRegistryReturnsOnCall map[int]struct {
		result1 *registry.Context
		result2 error
	}
	ParseManifestsStub        func(*imagepromotera.Options) ([]schema.Manifest, error)
	parseManifestsMutex       sync.RWMutex
	parseManifestsArgsForCall []FakePromoterImplementationParseManifestsArgs
	parseManifestsReturns     struct {
		result1 []schema.Manifest
		result2 error
	}
	parseManifestsReturnsOnCall map[int]struct {
		result1 []schema.Manifest
		result2 error
	}
	PrewarmTUFCacheStub        func(context.Context) error
	prewarmTUFCacheMutex       sync.RWMutex
	prewarmTUFCacheArgsForCall []FakePromoterImplementationPrewarmTUFCacheArgs
	prewarmTUFCacheReturns     struct {
		result1 error
	}
	prewarmTUFCacheReturnsOnCall map[int]struct {
		result1 error
	}
	PrintSecDisclaimerStub        func()
	printSecDisclaimerMutex       sync.RWMutex
	printSecDisclaimerArgsForCall []struct{}
	PrintVersionStub              func()
	printVersionMutex             sync.RWMutex
	printVersionArgsForCall       []struct{}
	PromoteImagesStub             func(context.Context, *imagepromotera.Options, map[promotion.Edge]any) error
	promoteImagesMutex            sync.RWMutex
	promoteImagesArgsForCall      []FakePromoterImplementationPromoteImagesArgs
	promoteImagesReturns          struct {
		result1 error
	}
	promoteImagesReturnsOnCall map[int]struct {
		result1 error
	}
	ScanEdgesStub        func(context.Context, *imagepromotera.Options, map[promotion.Edge]any) error
	scanEdgesMutex       sync.RWMutex
	scanEdgesArgsForCall []FakePromoterImplementationScanEdgesArgs
	scanEdgesReturns     struct {
		result1 error
	}
	scanEdgesReturnsOnCall map[int]struct {
		result1 error
	}
	SignImagesStub        func(*imagepromotera.Options, map[promotion.Edge]any) error
	signImagesMutex       sync.RWMutex
	signImagesArgsForCall []FakePromoterImplementationSignImagesArgs
	signImagesReturns     struct {
		result1 error
	}
	signImagesReturnsOnCall map[int]struct {
		result1 error
	}
	SnapshotStub        func(*imagepromotera.Options, registry.RegInvImage) error
	snapshotMutex       sync.RWMutex
	snapshotArgsForCall []FakePromoterImplementationSnapshotArgs
	snapshotReturns     struct {
		result1 error
	}
	snapshotReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOptionsStub        func(*imagepromotera.Options) error
	validateOptionsMutex       sync.RWMutex
	validateOptionsArgsForCall []FakePromoterImplementationValidateOptionsArgs
	validateOptionsReturns     struct {
		result1 error
	}
	validateOptionsReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateStagingSignaturesStub        func(context.Context, *imagepromotera.Options, map[promotion.Edge]any, map[string]*provenance.Discovery) (promotion.StagingSignatures, error)
	validateStagingSignaturesMutex       sync.RWMutex
	validateStagingSignaturesArgsForCall []FakePromoterImplementationValidateStagingSignaturesArgs
	validateStagingSignaturesReturns     struct {
		result1 promotion.StagingSignatures
		result2 error
	}
	validateStagingSignaturesReturnsOnCall map[int]struct {
		result1 promotion.StagingSignatures
		result2 error
	}
	WriteProvenanceAttestationsStub        func(context.Context, *imagepromotera.Options, []schema.Manifest, map[promotion.Edge]any, provenance.Generator) error
	writeProvenanceAttestationsMutex       sync.RWMutex
	writeProvenanceAttestationsArgsForCall []FakePromoterImplementationWriteProvenanceAttestationsArgs
	writeProvenanceAttestationsReturns     struct {
		result1 error
	}
	writeProvenanceAttestationsReturnsOnCall map[int]struct {
		result1 error
	}
	WriteVerificationSummariesStub        func(context.Context, *imagepromotera.Options, []schema.Manifest, map[promotion.Edge]any, map[string]*provenance.Discovery, map[string]*provenance.ImageProvenance) error
	writeVerificationSummariesMutex       sync.RWMutex
	writeVerificationSummariesArgsForCall []FakePromoterImplementationWriteVerificationSummariesArgs
	writeVerificationSummariesReturns     struct {
		result1 error
	}
	writeVerificationSummariesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakePromoterImplementationAppendManifestToSnapshotArgs holds the arguments of one call to AppendManifestToSnapshot.
type FakePromoterImplementationAppendManifestToSnapshotArgs struct {
	Arg1 *imagepromotera.Options
	Arg2 []schema.Manifest
}

// FakePromoterImplementationCarryAttestationsArgs holds the arguments of one call to CarryAttestations.
type FakePromoterImplementationCarryAttestationsArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 map[promotion.Edge]any
	Arg4 map[string]*provenance.ImageProvenance
}

// FakePromoterImplementationFixMissingAttestationsArgs holds the arguments of one call to FixMissingAttestations.
type FakePromoterImplementationFixMissingAttestationsArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 checkresults.Results
	Arg4 provenance.Generator
}

// FakePromoterImplementationFixMissingSignaturesArgs holds the arguments of one call to FixMissingSignatures.
type FakePromoterImplementationFixMissingSignaturesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 checkresults.Results
}

// FakePromoterImplementationGetLatestImagesArgs holds the arguments of one call to GetLatestImages.
type FakePromoterImplementationGetLatestImagesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
}

// FakePromoterImplementationGetPromotionEdgesArgs holds the arguments of one call to GetPromotionEdges.
type FakePromoterImplementationGetPromotionEdgesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 []schema.Manifest
}

// FakePromoterImplementationGetRegistryImageInventoryArgs holds the arguments of one call to GetRegistryImageInventory.
type FakePromoterImplementationGetRegistryImageInventoryArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 []schema.Manifest
}

// FakePromoterImplementationGetSignatureStatusArgs holds the arguments of one call to GetSignatureStatus.
type FakePromoterImplementationGetSignatureStatusArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 []checkresults.Image
}

// FakePromoterImplementationGetSnapshotManifestsArgs holds the arguments of one call to GetSnapshotManifests.
type FakePromoterImplementationGetSnapshotManifestsArgs struct {
	Arg1 *imagepromotera.Options
}

// FakePromoterImplementationGetSnapshotSourceRegistryArgs holds the arguments of one call to GetSnapshotSourceRegistry.
type FakePromoterImplementationGetSnapshotSourceRegistryArgs struct {
	Arg1 *imagepromotera.Options
}

// FakePromoterImplementationParseManifestsArgs holds the arguments of one call to ParseManifests.
type FakePromoterImplementationParseManifestsArgs struct {
	Arg1 *imagepromotera.Options
}

// FakePromoterImplementationPrewarmTUFCacheArgs holds the arguments of one call to PrewarmTUFCache.
type FakePromoterImplementationPrewarmTUFCacheArgs struct {
	Arg1 context.Context
}

// FakePromoterImplementationPromoteImagesArgs holds the arguments of one call to PromoteImages.
type FakePromoterImplementationPromoteImagesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 map[promotion.Edge]any
}

// FakePromoterImplementationScanEdgesArgs holds the arguments of one call to ScanEdges.
type FakePromoterImplementationScanEdgesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 map[promotion.Edge]any
}

// FakePromoterImplementationSignImagesArgs holds the arguments of one call to SignImages.
type FakePromoterImplementationSignImagesArgs struct {
	Arg1 *imagepromotera.Options
	Arg2 map[promotion.Edge]any
}

// FakePromoterImplementationSnapshotArgs holds the arguments of one call to Snapshot.
type FakePromoterImplementationSnapshotArgs struct {
	Arg1 *imagepromotera.Options
	Arg2 registry.RegInvImage
}

// FakePromoterImplementationValidateOptionsArgs holds the arguments of one call to ValidateOptions.
type FakePromoterImplementationValidateOptionsArgs struct {
	Arg1 *imagepromotera.Options
}

// FakePromoterImplementationValidateStagingSignaturesArgs holds the arguments of one call to ValidateStagingSignatures.
type FakePromoterImplementationValidateStagingSignaturesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 map[promotion.Edge]any
	Arg4 map[string]*provenance.Discovery
}

// FakePromoterImplementationWriteProvenanceAttestationsArgs holds the arguments of one call to WriteProvenanceAttestations.
type FakePromoterImplementationWriteProvenanceAttestationsArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 []schema.Manifest
	Arg4 map[promotion.Edge]any
	Arg5 provenance.Generator
}

// FakePromoterImplementationWriteVerificationSummariesArgs holds the arguments of one call to WriteVerificationSummaries.
type FakePromoterImplementationWriteVerificationSummariesArgs struct {
	Arg1 context.Context
	Arg2 *imagepromotera.Options
	Arg3 []schema.Manifest
	Arg4 map[promotion.Edge]any
	Arg5 map[string]*provenance.Discovery
	Arg6 map[string]*provenance.ImageProvenance
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshot(arg1 *imagepromotera.Options, arg2 []schema.Manifest) ([]schema.Manifest, error) {
	var arg2Copy []schema.Manifest
	if arg2 != nil {
		arg2Copy = make([]schema.Manifest, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.appendManifestToSnapshotMutex.Lock()
	ret, specificReturn := fake.appendManifestToSnapshotReturnsOnCall[len(fake.appendManifestToSnapshotArgsForCall)]
	fake.appendManifestToSnapshotArgsForCall = append(fake.appendManifestToSnapshotArgsForCall, FakePromoterImplementationAppendManifestToSnapshotArgs{arg1, arg2Copy})
	stub := fake.AppendManifestToSnapshotStub
	fakeReturns := fake.appendManifestToSnapshotReturns
	fake.recordInvocation("AppendManifestToSnapshot", []interface{}{arg1, arg2Copy})
	fake.appendManifestToSnapshotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotCallCount() int {
	fake.appendManifestToSnapshotMutex.RLock()
	defer fake.appendManifestToSnapshotMutex.RUnlock()
	return len(fake.appendManifestToSnapshotArgsForCall)
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotCalls(stub func(*imagepromotera.Options, []schema.Manifest) ([]schema.Manifest, error)) {
	fake.appendManifestToSnapshotMutex.Lock()
	defer fake.appendManifestToSnapshotMutex.Unlock()
	fake.AppendManifestToSnapshotStub = stub
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotArgsForCall(i int) (*imagepromotera.Options, []schema.Manifest) {
	fake.appendManifestToSnapshotMutex.RLock()
	defer fake.appendManifestToSnapshotMutex.RUnlock()
	argsForCall := fake.appendManifestToSnapshotArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotArgs() []FakePromoterImplementationAppendManifestToSnapshotArgs {
	fake.appendManifestToSnapshotMutex.RLock()
	defer fake.appendManifestToSnapshotMutex.RUnlock()
	args := make([]FakePromoterImplementationAppendManifestToSnapshotArgs, len(fake.appendManifestToSnapshotArgsForCall))
	copy(args, fake.appendManifestToSnapshotArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotReturns(result1 []schema.Manifest, result2 error) {
	fake.appendManifestToSnapshotMutex.Lock()
	defer fake.appendManifestToSnapshotMutex.Unlock()
	fake.AppendManifestToSnapshotStub = nil
	fake.appendManifestToSnapshotReturns = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) AppendManifestToSnapshotReturnsOnCall(i int, result1 []schema.Manifest, result2 error) {
	fake.appendManifestToSnapshotMutex.Lock()
	defer fake.appendManifestToSnapshotMutex.Unlock()
	fake.AppendManifestToSnapshotStub = nil
	if fake.appendManifestToSnapshotReturnsOnCall == nil {
		fake.appendManifestToSnapshotReturnsOnCall = make(map[int]struct {
			result1 []schema.Manifest
			result2 error
		})
	}
	fake.appendManifestToSnapshotReturnsOnCall[i] = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) CarryAttestations(arg1 context.Context, arg2 *imagepromotera.Options, arg3 map[promotion.Edge]any, arg4 map[string]*provenance.ImageProvenance) error {
	fake.carryAttestationsMutex.Lock()
	ret, specificReturn := fake.carryAttestationsReturnsOnCall[len(fake.carryAttestationsArgsForCall)]
	fake.carryAttestationsArgsForCall = append(fake.carryAttestationsArgsForCall, FakePromoterImplementationCarryAttestationsArgs{arg1, arg2, arg3, arg4})
	stub := fake.CarryAttestationsStub
	fakeReturns := fake.carryAttestationsReturns
	fake.recordInvocation("CarryAttestations", []interface{}{arg1, arg2, arg3, arg4})
	fake.carryAttestationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) CarryAttestationsCallCount() int {
	fake.carryAttestationsMutex.RLock()
	defer fake.carryAttestationsMutex.RUnlock()
	return len(fake.carryAttestationsArgsForCall)
}

func (fake *FakePromoterImplementation) CarryAttestationsCalls(stub func(context.Context, *imagepromotera.Options, map[promotion.Edge]any, map[string]*provenance.ImageProvenance) error) {
	fake.carryAttestationsMutex.Lock()
	defer fake.carryAttestationsMutex.Unlock()
	fake.CarryAttestationsStub = stub
}

func (fake *FakePromoterImplementation) CarryAttestationsArgsForCall(i int) (context.Context, *imagepromotera.Options, map[promotion.Edge]any, map[string]*provenance.ImageProvenance) {
	fake.carryAttestationsMutex.RLock()
	defer fake.carryAttestationsMutex.RUnlock()
	argsForCall := fake.carryAttestationsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakePromoterImplementation) CarryAttestationsArgs() []FakePromoterImplementationCarryAttestationsArgs {
	fake.carryAttestationsMutex.RLock()
	defer fake.carryAttestationsMutex.RUnlock()
	args := make([]FakePromoterImplementationCarryAttestationsArgs, len(fake.carryAttestationsArgsForCall))
	copy(args, fake.carryAttestationsArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) CarryAttestationsReturns(result1 error) {
	fake.carryAttestationsMutex.Lock()
	defer fake.carryAttestationsMutex.Unlock()
	fake.CarryAttestationsStub = nil
	fake.carryAttestationsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) CarryAttestationsReturnsOnCall(i int, result1 error) {
	fake.carryAttestationsMutex.Lock()
	defer fake.carryAttestationsMutex.Unlock()
	fake.CarryAttestationsStub = nil
	if fake.carryAttestationsReturnsOnCall == nil {
		fake.carryAttestationsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.carryAttestationsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixMissingAttestations(arg1 context.Context, arg2 *imagepromotera.Options, arg3 checkresults.Results, arg4 provenance.Generator) error {
	var arg3Copy checkresults.Results
	if arg3 != nil {
		arg3Copy = make(checkresults.Results, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.fixMissingAttestationsMutex.Lock()
	ret, specificReturn := fake.fixMissingAttestationsReturnsOnCall[len(fake.fixMissingAttestationsArgsForCall)]
	fake.fixMissingAttestationsArgsForCall = append(fake.fixMissingAttestationsArgsForCall, FakePromoterImplementationFixMissingAttestationsArgs{arg1, arg2, arg3Copy, arg4})
	stub := fake.FixMissingAttestationsStub
	fakeReturns := fake.fixMissingAttestationsReturns
	fake.recordInvocation("FixMissingAttestations", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.fixMissingAttestationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) FixMissingAttestationsCallCount() int {
	fake.fixMissingAttestationsMutex.RLock()
	defer fake.fixMissingAttestationsMutex.RUnlock()
	return len(fake.fixMissingAttestationsArgsForCall)
}

func (fake *FakePromoterImplementation) FixMissingAttestationsCalls(stub func(context.Context, *imagepromotera.Options, checkresults.Results, provenance.Generator) error) {
	fake.fixMissingAttestationsMutex.Lock()
	defer fake.fixMissingAttestationsMutex.Unlock()
	fake.FixMissingAttestationsStub = stub
}

func (fake *FakePromoterImplementation) FixMissingAttestationsArgsForCall(i int) (context.Context, *imagepromotera.Options, checkresults.Results, provenance.Generator) {
	fake.fixMissingAttestationsMutex.RLock()
	defer fake.fixMissingAttestationsMutex.RUnlock()
	argsForCall := fake.fixMissingAttestationsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakePromoterImplementation) FixMissingAttestationsArgs() []FakePromoterImplementationFixMissingAttestationsArgs {
	fake.fixMissingAttestationsMutex.RLock()
	defer fake.fixMissingAttestationsMutex.RUnlock()
	args := make([]FakePromoterImplementationFixMissingAttestationsArgs, len(fake.fixMissingAttestationsArgsForCall))
	copy(args, fake.fixMissingAttestationsArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) FixMissingAttestationsReturns(result1 error) {
	fake.fixMissingAttestationsMutex.Lock()
	defer fake.fixMissingAttestationsMutex.Unlock()
	fake.FixMissingAttestationsStub = nil
	fake.fixMissingAttestationsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixMissingAttestationsReturnsOnCall(i int, result1 error) {
	fake.fixMissingAttestationsMutex.Lock()
	defer fake.fixMissingAttestationsMutex.Unlock()
	fake.FixMissingAttestationsStub = nil
	if fake.fixMissingAttestationsReturnsOnCall == nil {
		fake.fixMissingAttestationsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fixMissingAttestationsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixMissingSignatures(arg1 context.Context, arg2 *imagepromotera.Options, arg3 checkresults.Results) error {
	var arg3Copy checkresults.Results
	if arg3 != nil {
		arg3Copy = make(checkresults.Results, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.fixMissingSignaturesMutex.Lock()
	ret, specificReturn := fake.fixMissingSignaturesReturnsOnCall[len(fake.fixMissingSignaturesArgsForCall)]
	fake.fixMissingSignaturesArgsForCall = append(fake.fixMissingSignaturesArgsForCall, FakePromoterImplementationFixMissingSignaturesArgs{arg1, arg2, arg3Copy})
	stub := fake.FixMissingSignaturesStub
	fakeReturns := fake.fixMissingSignaturesReturns
	fake.recordInvocation("FixMissingSignatures", []interface{}{arg1, arg2, arg3Copy})
	fake.fixMissingSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) FixMissingSignaturesCallCount() int {
	fake.fixMissingSignaturesMutex.RLock()
	defer fake.fixMissingSignaturesMutex.RUnlock()
	return len(fake.fixMissingSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) FixMissingSignaturesCalls(stub func(context.Context, *imagepromotera.Options, checkresults.Results) error) {
	fake.fixMissingSignaturesMutex.Lock()
	defer fake.fixMissingSignaturesMutex.Unlock()
	fake.FixMissingSignaturesStub = stub
}

func (fake *FakePromoterImplementation) FixMissingSignaturesArgsForCall(i int) (context.Context, *imagepromotera.Options, checkresults.Results) {
	fake.fixMissingSignaturesMutex.RLock()
	defer fake.fixMissingSignaturesMutex.RUnlock()
	argsForCall := fake.fixMissingSignaturesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakePromoterImplementation) FixMissingSignaturesArgs() []FakePromoterImplementationFixMissingSignaturesArgs {
	fake.fixMissingSignaturesMutex.RLock()
	defer fake.fixMissingSignaturesMutex.RUnlock()
	args := make([]FakePromoterImplementationFixMissingSignaturesArgs, len(fake.fixMissingSignaturesArgsForCall))
	copy(args, fake.fixMissingSignaturesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) FixMissingSignaturesReturns(result1 error) {
	fake.fixMissingSignaturesMutex.Lock()
	defer fake.fixMissingSignaturesMutex.Unlock()
	fake.FixMissingSignaturesStub = nil
	fake.fixMissingSignaturesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) FixMissingSignaturesReturnsOnCall(i int, result1 error) {
	fake.fixMissingSignaturesMutex.Lock()
	defer fake.fixMissingSignaturesMutex.Unlock()
	fake.FixMissingSignaturesStub = nil
	if fake.fixMissingSignaturesReturnsOnCall == nil {
		fake.fixMissingSignaturesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fixMissingSignaturesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) GetLatestImages(arg1 context.Context, arg2 *imagepromotera.Options) ([]checkresults.Image, error) {
	fake.getLatestImagesMutex.Lock()
	ret, specificReturn := fake.getLatestImagesReturnsOnCall[len(fake.getLatestImagesArgsForCall)]
	fake.getLatestImagesArgsForCall = append(fake.getLatestImagesArgsForCall, FakePromoterImplementationGetLatestImagesArgs{arg1, arg2})
	stub := fake.GetLatestImagesStub
	fakeReturns := fake.getLatestImagesReturns
	fake.recordInvocation("GetLatestImages", []interface{}{arg1, arg2})
	fake.getLatestImagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetLatestImagesCallCount() int {
	fake.getLatestImagesMutex.RLock()
	defer fake.getLatestImagesMutex.RUnlock()
	return len(fake.getLatestImagesArgsForCall)
}

func (fake *FakePromoterImplementation) GetLatestImagesCalls(stub func(context.Context, *imagepromotera.Options) ([]checkresults.Image, error)) {
	fake.getLatestImagesMutex.Lock()
	defer fake.getLatestImagesMutex.Unlock()
	fake.GetLatestImagesStub = stub
}

func (fake *FakePromoterImplementation) GetLatestImagesArgsForCall(i int) (context.Context, *imagepromotera.Options) {
	fake.getLatestImagesMutex.RLock()
	defer fake.getLatestImagesMutex.RUnlock()
	argsForCall := fake.getLatestImagesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakePromoterImplementation) GetLatestImagesArgs() []FakePromoterImplementationGetLatestImagesArgs {
	fake.getLatestImagesMutex.RLock()
	defer fake.getLatestImagesMutex.RUnlock()
	args := make([]FakePromoterImplementationGetLatestImagesArgs, len(fake.getLatestImagesArgsForCall))
	copy(args, fake.getLatestImagesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) GetLatestImagesReturns(result1 []checkresults.Image, result2 error) {
	fake.getLatestImagesMutex.Lock()
	defer fake.getLatestImagesMutex.Unlock()
	fake.GetLatestImagesStub = nil
	fake.getLatestImagesReturns = struct {
		result1 []checkresults.Image
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetLatestImagesReturnsOnCall(i int, result1 []checkresults.Image, result2 error) {
	fake.getLatestImagesMutex.Lock()
	defer fake.getLatestImagesMutex.Unlock()
	fake.GetLatestImagesStub = nil
	if fake.getLatestImagesReturnsOnCall == nil {
		fake.getLatestImagesReturnsOnCall = make(map[int]struct {
			result1 []checkresults.Image
			result2 error
		})
	}
	fake.getLatestImagesReturnsOnCall[i] = struct {
		result1 []checkresults.Image
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetPromotionEdges(arg1 context.Context, arg2 *imagepromotera.Options, arg3 []schema.Manifest) (map[promotion.Edge]any, error) {
	var arg3Copy []schema.Manifest
	if arg3 != nil {
		arg3Copy = make([]schema.Manifest, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.getPromotionEdgesMutex.Lock()
	ret, specificReturn := fake.getPromotionEdgesReturnsOnCall[len(fake.getPromotionEdgesArgsForCall)]
	fake.getPromotionEdgesArgsForCall = append(fake.getPromotionEdgesArgsForCall, FakePromoterImplementationGetPromotionEdgesArgs{arg1, arg2, arg3Copy})
	stub := fake.GetPromotionEdgesStub
	fakeReturns := fake.getPromotionEdgesReturns
	fake.recordInvocation("GetPromotionEdges", []interface{}{arg1, arg2, arg3Copy})
	fake.getPromotionEdgesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetPromotionEdgesCallCount() int {
	fake.getPromotionEdgesMutex.RLock()
	defer fake.getPromotionEdgesMutex.RUnlock()
	return len(fake.getPromotionEdgesArgsForCall)
}

func (fake *FakePromoterImplementation) GetPromotionEdgesCalls(stub func(context.Context, *imagepromotera.Options, []schema.Manifest) (map[promotion.Edge]any, error)) {
	fake.getPromotionEdgesMutex.Lock()
	defer fake.getPromotionEdgesMutex.Unlock()
	fake.GetPromotionEdgesStub = stub
}

func (fake *FakePromoterImplementation) GetPromotionEdgesArgsForCall(i int) (context.Context, *imagepromotera.Options, []schema.Manifest) {
	fake.getPromotionEdgesMutex.RLock()
	defer fake.getPromotionEdgesMutex.RUnlock()
	argsForCall := fake.getPromotionEdgesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakePromoterImplementation) GetPromotionEdgesArgs() []FakePromoterImplementationGetPromotionEdgesArgs {
	fake.getPromotionEdgesMutex.RLock()
	defer fake.getPromotionEdgesMutex.RUnlock()
	args := make([]FakePromoterImplementationGetPromotionEdgesArgs, len(fake.getPromotionEdgesArgsForCall))
	copy(args, fake.getPromotionEdgesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) GetPromotionEdgesReturns(result1 map[promotion.Edge]any, result2 error) {
	fake.getPromotionEdgesMutex.Lock()
	defer fake.getPromotionEdgesMutex.Unlock()
	fake.GetPromotionEdgesStub = nil
	fake.getPromotionEdgesReturns = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetPromotionEdgesReturnsOnCall(i int, result1 map[promotion.Edge]any, result2 error) {
	fake.getPromotionEdgesMutex.Lock()
	defer fake.getPromotionEdgesMutex.Unlock()
	fake.GetPromotionEdgesStub = nil
	if fake.getPromotionEdgesReturnsOnCall == nil {
		fake.getPromotionEdgesReturnsOnCall = make(map[int]struct {
			result1 map[promotion.Edge]any
			result2 error
		})
	}
	fake.getPromotionEdgesReturnsOnCall[i] = struct {
		result1 map[promotion.Edge]any
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetRegistryImageInventory(arg1 context.Context, arg2 *imagepromotera.Options, arg3 []schema.Manifest) (registry.RegInvImage, error) {
	var arg3Copy []schema.Manifest
	if arg3 != nil {
		arg3Copy = make([]schema.Manifest, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.getRegistryImageInventoryMutex.Lock()
	ret, specificReturn := fake.getRegistryImageInventoryReturnsOnCall[len(fake.getRegistryImageInventoryArgsForCall)]
	fake.getRegistryImageInventoryArgsForCall = append(fake.getRegistryImageInventoryArgsForCall, FakePromoterImplementationGetRegistryImageInventoryArgs{arg1, arg2, arg3Copy})
	stub := fake.GetRegistryImageInventoryStub
	fakeReturns := fake.getRegistryImageInventoryReturns
	fake.recordInvocation("GetRegistryImageInventory", []interface{}{arg1, arg2, arg3Copy})
	fake.getRegistryImageInventoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryCallCount() int {
	fake.getRegistryImageInventoryMutex.RLock()
	defer fake.getRegistryImageInventoryMutex.RUnlock()
	return len(fake.getRegistryImageInventoryArgsForCall)
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryCalls(stub func(context.Context, *imagepromotera.Options, []schema.Manifest) (registry.RegInvImage, error)) {
	fake.getRegistryImageInventoryMutex.Lock()
	defer fake.getRegistryImageInventoryMutex.Unlock()
	fake.GetRegistryImageInventoryStub = stub
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryArgsForCall(i int) (context.Context, *imagepromotera.Options, []schema.Manifest) {
	fake.getRegistryImageInventoryMutex.RLock()
	defer fake.getRegistryImageInventoryMutex.RUnlock()
	argsForCall := fake.getRegistryImageInventoryArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryArgs() []FakePromoterImplementationGetRegistryImageInventoryArgs {
	fake.getRegistryImageInventoryMutex.RLock()
	defer fake.getRegistryImageInventoryMutex.RUnlock()
	args := make([]FakePromoterImplementationGetRegistryImageInventoryArgs, len(fake.getRegistryImageInventoryArgsForCall))
	copy(args, fake.getRegistryImageInventoryArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryReturns(result1 registry.RegInvImage, result2 error) {
	fake.getRegistryImageInventoryMutex.Lock()
	defer fake.getRegistryImageInventoryMutex.Unlock()
	fake.GetRegistryImageInventoryStub = nil
	fake.getRegistryImageInventoryReturns = struct {
		result1 registry.RegInvImage
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetRegistryImageInventoryReturnsOnCall(i int, result1 registry.RegInvImage, result2 error) {
	fake.getRegistryImageInventoryMutex.Lock()
	defer fake.getRegistryImageInventoryMutex.Unlock()
	fake.GetRegistryImageInventoryStub = nil
	if fake.getRegistryImageInventoryReturnsOnCall == nil {
		fake.getRegistryImageInventoryReturnsOnCall = make(map[int]struct {
			result1 registry.RegInvImage
			result2 error
		})
	}
	fake.getRegistryImageInventoryReturnsOnCall[i] = struct {
		result1 registry.RegInvImage
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSignatureStatus(arg1 context.Context, arg2 *imagepromotera.Options, arg3 []checkresults.Image) (checkresults.Results, error) {
	var arg3Copy []checkresults.Image
	if arg3 != nil {
		arg3Copy = make([]checkresults.Image, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.getSignatureStatusMutex.Lock()
	ret, specificReturn := fake.getSignatureStatusReturnsOnCall[len(fake.getSignatureStatusArgsForCall)]
	fake.getSignatureStatusArgsForCall = append(fake.getSignatureStatusArgsForCall, FakePromoterImplementationGetSignatureStatusArgs{arg1, arg2, arg3Copy})
	stub := fake.GetSignatureStatusStub
	fakeReturns := fake.getSignatureStatusReturns
	fake.recordInvocation("GetSignatureStatus", []interface{}{arg1, arg2, arg3Copy})
	fake.getSignatureStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetSignatureStatusCallCount() int {
	fake.getSignatureStatusMutex.RLock()
	defer fake.getSignatureStatusMutex.RUnlock()
	return len(fake.getSignatureStatusArgsForCall)
}

func (fake *FakePromoterImplementation) GetSignatureStatusCalls(stub func(context.Context, *imagepromotera.Options, []checkresults.Image) (checkresults.Results, error)) {
	fake.getSignatureStatusMutex.Lock()
	defer fake.getSignatureStatusMutex.Unlock()
	fake.GetSignatureStatusStub = stub
}

func (fake *FakePromoterImplementation) GetSignatureStatusArgsForCall(i int) (context.Context, *imagepromotera.Options, []checkresults.Image) {
	fake.getSignatureStatusMutex.RLock()
	defer fake.getSignatureStatusMutex.RUnlock()
	argsForCall := fake.getSignatureStatusArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakePromoterImplementation) GetSignatureStatusArgs() []FakePromoterImplementationGetSignatureStatusArgs {
	fake.getSignatureStatusMutex.RLock()
	defer fake.getSignatureStatusMutex.RUnlock()
	args := make([]FakePromoterImplementationGetSignatureStatusArgs, len(fake.getSignatureStatusArgsForCall))
	copy(args, fake.getSignatureStatusArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) GetSignatureStatusReturns(result1 checkresults.Results, result2 error) {
	fake.getSignatureStatusMutex.Lock()
	defer fake.getSignatureStatusMutex.Unlock()
	fake.GetSignatureStatusStub = nil
	fake.getSignatureStatusReturns = struct {
		result1 checkresults.Results
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSignatureStatusReturnsOnCall(i int, result1 checkresults.Results, result2 error) {
	fake.getSignatureStatusMutex.Lock()
	defer fake.getSignatureStatusMutex.Unlock()
	fake.GetSignatureStatusStub = nil
	if fake.getSignatureStatusReturnsOnCall == nil {
		fake.getSignatureStatusReturnsOnCall = make(map[int]struct {
			result1 checkresults.Results
			result2 error
		})
	}
	fake.getSignatureStatusReturnsOnCall[i] = struct {
		result1 checkresults.Results
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotManifests(arg1 *imagepromotera.Options) ([]schema.Manifest, error) {
	fake.getSnapshotManifestsMutex.Lock()
	ret, specificReturn := fake.getSnapshotManifestsReturnsOnCall[len(fake.getSnapshotManifestsArgsForCall)]
	fake.getSnapshotManifestsArgsForCall = append(fake.getSnapshotManifestsArgsForCall, FakePromoterImplementationGetSnapshotManifestsArgs{arg1})
	stub := fake.GetSnapshotManifestsStub
	fakeReturns := fake.getSnapshotManifestsReturns
	fake.recordInvocation("GetSnapshotManifests", []interface{}{arg1})
	fake.getSnapshotManifestsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsCallCount() int {
	fake.getSnapshotManifestsMutex.RLock()
	defer fake.getSnapshotManifestsMutex.RUnlock()
	return len(fake.getSnapshotManifestsArgsForCall)
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsCalls(stub func(*imagepromotera.Options) ([]schema.Manifest, error)) {
	fake.getSnapshotManifestsMutex.Lock()
	defer fake.getSnapshotManifestsMutex.Unlock()
	fake.GetSnapshotManifestsStub = stub
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsArgsForCall(i int) *imagepromotera.Options {
	fake.getSnapshotManifestsMutex.RLock()
	defer fake.getSnapshotManifestsMutex.RUnlock()
	argsForCall := fake.getSnapshotManifestsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsArgs() []FakePromoterImplementationGetSnapshotManifestsArgs {
	fake.getSnapshotManifestsMutex.RLock()
	defer fake.getSnapshotManifestsMutex.RUnlock()
	args := make([]FakePromoterImplementationGetSnapshotManifestsArgs, len(fake.getSnapshotManifestsArgsForCall))
	copy(args, fake.getSnapshotManifestsArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsReturns(result1 []schema.Manifest, result2 error) {
	fake.getSnapshotManifestsMutex.Lock()
	defer fake.getSnapshotManifestsMutex.Unlock()
	fake.GetSnapshotManifestsStub = nil
	fake.getSnapshotManifestsReturns = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotManifestsReturnsOnCall(i int, result1 []schema.Manifest, result2 error) {
	fake.getSnapshotManifestsMutex.Lock()
	defer fake.getSnapshotManifestsMutex.Unlock()
	fake.GetSnapshotManifestsStub = nil
	if fake.getSnapshotManifestsReturnsOnCall == nil {
		fake.getSnapshotManifestsReturnsOnCall = make(map[int]struct {
			result1 []schema.Manifest
			result2 error
		})
	}
	fake.getSnapshotManifestsReturnsOnCall[i] = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistry(arg1 *imagepromotera.Options) (*registry.Context, error) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	ret, specificReturn := fake.getSnapshotSourceRegistryReturnsOnCall[len(fake.getSnapshotSourceRegistryArgsForCall)]
	fake.getSnapshotSourceRegistryArgsForCall = append(fake.getSnapshotSourceRegistryArgsForCall, FakePromoterImplementationGetSnapshotSourceRegistryArgs{arg1})
	stub := fake.GetSnapshotSourceRegistryStub
	fakeReturns := fake.getSnapshotSourceRegistryReturns
	fake.recordInvocation("GetSnapshotSourceRegistry", []interface{}{arg1})
	fake.getSnapshotSourceRegistryMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryCallCount() int {
	fake.getSnapshotSourceRegistryMutex.RLock()
	defer fake.getSnapshotSourceRegistryMutex.RUnlock()
	return len(fake.getSnapshotSourceRegistryArgsForCall)
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryCalls(stub func(*imagepromotera.Options) (*registry.Context, error)) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	defer fake.getSnapshotSourceRegistryMutex.Unlock()
	fake.GetSnapshotSourceRegistryStub = stub
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryArgsForCall(i int) *imagepromotera.Options {
	fake.getSnapshotSourceRegistryMutex.RLock()
	defer fake.getSnapshotSourceRegistryMutex.RUnlock()
	argsForCall := fake.getSnapshotSourceRegistryArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryArgs() []FakePromoterImplementationGetSnapshotSourceRegistryArgs {
	fake.getSnapshotSourceRegistryMutex.RLock()
	defer fake.getSnapshotSourceRegistryMutex.RUnlock()
	args := make([]FakePromoterImplementationGetSnapshotSourceRegistryArgs, len(fake.getSnapshotSourceRegistryArgsForCall))
	copy(args, fake.getSnapshotSourceRegistryArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryReturns(result1 *registry.Context, result2 error) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	defer fake.getSnapshotSourceRegistryMutex.Unlock()
	fake.GetSnapshotSourceRegistryStub = nil
	fake.getSnapshotSourceRegistryReturns = struct {
		result1 *registry.Context
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) GetSnapshotSourceRegistryReturnsOnCall(i int, result1 *registry.Context, result2 error) {
	fake.getSnapshotSourceRegistryMutex.Lock()
	defer fake.getSnapshotSourceRegistryMutex.Unlock()
	fake.GetSnapshotSourceRegistryStub = nil
	if fake.getSnapshotSourceRegistryReturnsOnCall == nil {
		fake.getSnapshotSourceRegistryReturnsOnCall = make(map[int]struct {
			result1 *registry.Context
			result2 error
		})
	}
	fake.getSnapshotSourceRegistryReturnsOnCall[i] = struct {
		result1 *registry.Context
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) ParseManifests(arg1 *imagepromotera.Options) ([]schema.Manifest, error) {
	fake.parseManifestsMutex.Lock()
	ret, specificReturn := fake.parseManifestsReturnsOnCall[len(fake.parseManifestsArgsForCall)]
	fake.parseManifestsArgsForCall = append(fake.parseManifestsArgsForCall, FakePromoterImplementationParseManifestsArgs{arg1})
	stub := fake.ParseManifestsStub
	fakeReturns := fake.parseManifestsReturns
	fake.recordInvocation("ParseManifests", []interface{}{arg1})
	fake.parseManifestsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) ParseManifestsCallCount() int {
	fake.parseManifestsMutex.RLock()
	defer fake.parseManifestsMutex.RUnlock()
	return len(fake.parseManifestsArgsForCall)
}

func (fake *FakePromoterImplementation) ParseManifestsCalls(stub func(*imagepromotera.Options) ([]schema.Manifest, error)) {
	fake.parseManifestsMutex.Lock()
	defer fake.parseManifestsMutex.Unlock()
	fake.ParseManifestsStub = stub
}

func (fake *FakePromoterImplementation) ParseManifestsArgsForCall(i int) *imagepromotera.Options {
	fake.parseManifestsMutex.RLock()
	defer fake.parseManifestsMutex.RUnlock()
	argsForCall := fake.parseManifestsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakePromoterImplementation) ParseManifestsArgs() []FakePromoterImplementationParseManifestsArgs {
	fake.parseManifestsMutex.RLock()
	defer fake.parseManifestsMutex.RUnlock()
	args := make([]FakePromoterImplementationParseManifestsArgs, len(fake.parseManifestsArgsForCall))
	copy(args, fake.parseManifestsArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) ParseManifestsReturns(result1 []schema.Manifest, result2 error) {
	fake.parseManifestsMutex.Lock()
	defer fake.parseManifestsMutex.Unlock()
	fake.ParseManifestsStub = nil
	fake.parseManifestsReturns = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) ParseManifestsReturnsOnCall(i int, result1 []schema.Manifest, result2 error) {
	fake.parseManifestsMutex.Lock()
	defer fake.parseManifestsMutex.Unlock()
	fake.ParseManifestsStub = nil
	if fake.parseManifestsReturnsOnCall == nil {
		fake.parseManifestsReturnsOnCall = make(map[int]struct {
			result1 []schema.Manifest
			result2 error
		})
	}
	fake.parseManifestsReturnsOnCall[i] = struct {
		result1 []schema.Manifest
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) PrewarmTUFCache(arg1 context.Context) error {
	fake.prewarmTUFCacheMutex.Lock()
	ret, specificReturn := fake.prewarmTUFCacheReturnsOnCall[len(fake.prewarmTUFCacheArgsForCall)]
	fake.prewarmTUFCacheArgsForCall = append(fake.prewarmTUFCacheArgsForCall, FakePromoterImplementationPrewarmTUFCacheArgs{arg1})
	stub := fake.PrewarmTUFCacheStub
	fakeReturns := fake.prewarmTUFCacheReturns
	fake.recordInvocation("PrewarmTUFCache", []interface{}{arg1})
	fake.prewarmTUFCacheMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheCallCount() int {
	fake.prewarmTUFCacheMutex.RLock()
	defer fake.prewarmTUFCacheMutex.RUnlock()
	return len(fake.prewarmTUFCacheArgsForCall)
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheCalls(stub func(context.Context) error) {
	fake.prewarmTUFCacheMutex.Lock()
	defer fake.prewarmTUFCacheMutex.Unlock()
	fake.PrewarmTUFCacheStub = stub
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheArgsForCall(i int) context.Context {
	fake.prewarmTUFCacheMutex.RLock()
	defer fake.prewarmTUFCacheMutex.RUnlock()
	argsForCall := fake.prewarmTUFCacheArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheArgs() []FakePromoterImplementationPrewarmTUFCacheArgs {
	fake.prewarmTUFCacheMutex.RLock()
	defer fake.prewarmTUFCacheMutex.RUnlock()
	args := make([]FakePromoterImplementationPrewarmTUFCacheArgs, len(fake.prewarmTUFCacheArgsForCall))
	copy(args, fake.prewarmTUFCacheArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheReturns(result1 error) {
	fake.prewarmTUFCacheMutex.Lock()
	defer fake.prewarmTUFCacheMutex.Unlock()
	fake.PrewarmTUFCacheStub = nil
	fake.prewarmTUFCacheReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) PrewarmTUFCacheReturnsOnCall(i int, result1 error) {
	fake.prewarmTUFCacheMutex.Lock()
	defer fake.prewarmTUFCacheMutex.Unlock()
	fake.PrewarmTUFCacheStub = nil
	if fake.prewarmTUFCacheReturnsOnCall == nil {
		fake.prewarmTUFCacheReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.prewarmTUFCacheReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) PrintSecDisclaimer() {
	fake.printSecDisclaimerMutex.Lock()
	fake.printSecDisclaimerArgsForCall = append(fake.printSecDisclaimerArgsForCall, struct{}{})
	stub := fake.PrintSecDisclaimerStub
	fake.recordInvocation("PrintSecDisclaimer", []interface{}{})
	fake.printSecDisclaimerMutex.Unlock()
	if stub != nil {
		stub()
	}
}

func (fake *FakePromoterImplementation) PrintSecDisclaimerCallCount() int {
	fake.printSecDisclaimerMutex.RLock()
	defer fake.printSecDisclaimerMutex.RUnlock()
	return len(fake.printSecDisclaimerArgsForCall)
}

func (fake *FakePromoterImplementation) PrintSecDisclaimerCalls(stub func()) {
	fake.printSecDisclaimerMutex.Lock()
	defer fake.printSecDisclaimerMutex.Unlock()
	fake.PrintSecDisclaimerStub = stub
}

func (fake *FakePromoterImplementation) PrintVersion() {
	fake.printVersionMutex.Lock()
	fake.printVersionArgsForCall = append(fake.printVersionArgsForCall, struct{}{})
	stub := fake.PrintVersionStub
	fake.recordInvocation("PrintVersion", []interface{}{})
	fake.printVersionMutex.Unlock()
	if stub != nil {
		stub()
	}
}

func (fake *FakePromoterImplementation) PrintVersionCallCount() int {
	fake.printVersionMutex.RLock()
	defer fake.printVersionMutex.RUnlock()
	return len(fake.printVersionArgsForCall)
}

func (fake *FakePromoterImplementation) PrintVersionCalls(stub func()) {
	fake.printVersionMutex.Lock()
	defer fake.printVersionMutex.Unlock()
	fake.PrintVersionStub = stub
}

func (fake *FakePromoterImplementation) PromoteImages(arg1 context.Context, arg2 *imagepromotera.Options, arg3 map[promotion.Edge]any) error {
	fake.promoteImagesMutex.Lock()
	ret, specificReturn := fake.promoteImagesReturnsOnCall[len(fake.promoteImagesArgsForCall)]
	fake.promoteImagesArgsForCall = append(fake.promoteImagesArgsForCall, FakePromoterImplementationPromoteImagesArgs{arg1, arg2, arg3})
	stub := fake.PromoteImagesStub
	fakeReturns := fake.promoteImagesReturns
	fake.recordInvocation("PromoteImages", []interface{}{arg1, arg2, arg3})
	fake.promoteImagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) PromoteImagesCallCount() int {
	fake.promoteImagesMutex.RLock()
	defer fake.promoteImagesMutex.RUnlock()
	return len(fake.promoteImagesArgsForCall)
}

func (fake *FakePromoterImplementation) PromoteImagesCalls(stub func(context.Context, *imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.promoteImagesMutex.Lock()
	defer fake.promoteImagesMutex.Unlock()
	fake.PromoteImagesStub = stub
}

func (fake *FakePromoterImplementation) PromoteImagesArgsForCall(i int) (context.Context, *imagepromotera.Options, map[promotion.Edge]any) {
	fake.promoteImagesMutex.RLock()
	defer fake.promoteImagesMutex.RUnlock()
	argsForCall := fake.promoteImagesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakePromoterImplementation) PromoteImagesArgs() []FakePromoterImplementationPromoteImagesArgs {
	fake.promoteImagesMutex.RLock()
	defer fake.promoteImagesMutex.RUnlock()
	args := make([]FakePromoterImplementationPromoteImagesArgs, len(fake.promoteImagesArgsForCall))
	copy(args, fake.promoteImagesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) PromoteImagesReturns(result1 error) {
	fake.promoteImagesMutex.Lock()
	defer fake.promoteImagesMutex.Unlock()
	fake.PromoteImagesStub = nil
	fake.promoteImagesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) PromoteImagesReturnsOnCall(i int, result1 error) {
	fake.promoteImagesMutex.Lock()
	defer fake.promoteImagesMutex.Unlock()
	fake.PromoteImagesStub = nil
	if fake.promoteImagesReturnsOnCall == nil {
		fake.promoteImagesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.promoteImagesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ScanEdges(arg1 context.Context, arg2 *imagepromotera.Options, arg3 map[promotion.Edge]any) error {
	fake.scanEdgesMutex.Lock()
	ret, specificReturn := fake.scanEdgesReturnsOnCall[len(fake.scanEdgesArgsForCall)]
	fake.scanEdgesArgsForCall = append(fake.scanEdgesArgsForCall, FakePromoterImplementationScanEdgesArgs{arg1, arg2, arg3})
	stub := fake.ScanEdgesStub
	fakeReturns := fake.scanEdgesReturns
	fake.recordInvocation("ScanEdges", []interface{}{arg1, arg2, arg3})
	fake.scanEdgesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) ScanEdgesCallCount() int {
	fake.scanEdgesMutex.RLock()
	defer fake.scanEdgesMutex.RUnlock()
	return len(fake.scanEdgesArgsForCall)
}

func (fake *FakePromoterImplementation) ScanEdgesCalls(stub func(context.Context, *imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.scanEdgesMutex.Lock()
	defer fake.scanEdgesMutex.Unlock()
	fake.ScanEdgesStub = stub
}

func (fake *FakePromoterImplementation) ScanEdgesArgsForCall(i int) (context.Context, *imagepromotera.Options, map[promotion.Edge]any) {
	fake.scanEdgesMutex.RLock()
	defer fake.scanEdgesMutex.RUnlock()
	argsForCall := fake.scanEdgesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakePromoterImplementation) ScanEdgesArgs() []FakePromoterImplementationScanEdgesArgs {
	fake.scanEdgesMutex.RLock()
	defer fake.scanEdgesMutex.RUnlock()
	args := make([]FakePromoterImplementationScanEdgesArgs, len(fake.scanEdgesArgsForCall))
	copy(args, fake.scanEdgesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) ScanEdgesReturns(result1 error) {
	fake.scanEdgesMutex.Lock()
	defer fake.scanEdgesMutex.Unlock()
	fake.ScanEdgesStub = nil
	fake.scanEdgesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ScanEdgesReturnsOnCall(i int, result1 error) {
	fake.scanEdgesMutex.Lock()
	defer fake.scanEdgesMutex.Unlock()
	fake.ScanEdgesStub = nil
	if fake.scanEdgesReturnsOnCall == nil {
		fake.scanEdgesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.scanEdgesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) SignImages(arg1 *imagepromotera.Options, arg2 map[promotion.Edge]any) error {
	fake.signImagesMutex.Lock()
	ret, specificReturn := fake.signImagesReturnsOnCall[len(fake.signImagesArgsForCall)]
	fake.signImagesArgsForCall = append(fake.signImagesArgsForCall, FakePromoterImplementationSignImagesArgs{arg1, arg2})
	stub := fake.SignImagesStub
	fakeReturns := fake.signImagesReturns
	fake.recordInvocation("SignImages", []interface{}{arg1, arg2})
	fake.signImagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) SignImagesCallCount() int {
	fake.signImagesMutex.RLock()
	defer fake.signImagesMutex.RUnlock()
	return len(fake.signImagesArgsForCall)
}

func (fake *FakePromoterImplementation) SignImagesCalls(stub func(*imagepromotera.Options, map[promotion.Edge]any) error) {
	fake.signImagesMutex.Lock()
	defer fake.signImagesMutex.Unlock()
	fake.SignImagesStub = stub
}

func (fake *FakePromoterImplementation) SignImagesArgsForCall(i int) (*imagepromotera.Options, map[promotion.Edge]any) {
	fake.signImagesMutex.RLock()
	defer fake.signImagesMutex.RUnlock()
	argsForCall := fake.signImagesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakePromoterImplementation) SignImagesArgs() []FakePromoterImplementationSignImagesArgs {
	fake.signImagesMutex.RLock()
	defer fake.signImagesMutex.RUnlock()
	args := make([]FakePromoterImplementationSignImagesArgs, len(fake.signImagesArgsForCall))
	copy(args, fake.signImagesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) SignImagesReturns(result1 error) {
	fake.signImagesMutex.Lock()
	defer fake.signImagesMutex.Unlock()
	fake.SignImagesStub = nil
	fake.signImagesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) SignImagesReturnsOnCall(i int, result1 error) {
	fake.signImagesMutex.Lock()
	defer fake.signImagesMutex.Unlock()
	fake.SignImagesStub = nil
	if fake.signImagesReturnsOnCall == nil {
		fake.signImagesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.signImagesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) Snapshot(arg1 *imagepromotera.Options, arg2 registry.RegInvImage) error {
	fake.snapshotMutex.Lock()
	ret, specificReturn := fake.snapshotReturnsOnCall[len(fake.snapshotArgsForCall)]
	fake.snapshotArgsForCall = append(fake.snapshotArgsForCall, FakePromoterImplementationSnapshotArgs{arg1, arg2})
	stub := fake.SnapshotStub
	fakeReturns := fake.snapshotReturns
	fake.recordInvocation("Snapshot", []interface{}{arg1, arg2})
	fake.snapshotMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) SnapshotCallCount() int {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	return len(fake.snapshotArgsForCall)
}

func (fake *FakePromoterImplementation) SnapshotCalls(stub func(*imagepromotera.Options, registry.RegInvImage) error) {
	fake.snapshotMutex.Lock()
	defer fake.snapshotMutex.Unlock()
	fake.SnapshotStub = stub
}

func (fake *FakePromoterImplementation) SnapshotArgsForCall(i int) (*imagepromotera.Options, registry.RegInvImage) {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	argsForCall := fake.snapshotArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2
}

func (fake *FakePromoterImplementation) SnapshotArgs() []FakePromoterImplementationSnapshotArgs {
	fake.snapshotMutex.RLock()
	defer fake.snapshotMutex.RUnlock()
	args := make([]FakePromoterImplementationSnapshotArgs, len(fake.snapshotArgsForCall))
	copy(args, fake.snapshotArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) SnapshotReturns(result1 error) {
	fake.snapshotMutex.Lock()
	defer fake.snapshotMutex.Unlock()
	fake.SnapshotStub = nil
	fake.snapshotReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) SnapshotReturnsOnCall(i int, result1 error) {
	fake.snapshotMutex.Lock()
	defer fake.snapshotMutex.Unlock()
	fake.SnapshotStub = nil
	if fake.snapshotReturnsOnCall == nil {
		fake.snapshotReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.snapshotReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ValidateOptions(arg1 *imagepromotera.Options) error {
	fake.validateOptionsMutex.Lock()
	ret, specificReturn := fake.validateOptionsReturnsOnCall[len(fake.validateOptionsArgsForCall)]
	fake.validateOptionsArgsForCall = append(fake.validateOptionsArgsForCall, FakePromoterImplementationValidateOptionsArgs{arg1})
	stub := fake.ValidateOptionsStub
	fakeReturns := fake.validateOptionsReturns
	fake.recordInvocation("ValidateOptions", []interface{}{arg1})
	fake.validateOptionsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) ValidateOptionsCallCount() int {
	fake.validateOptionsMutex.RLock()
	defer fake.validateOptionsMutex.RUnlock()
	return len(fake.validateOptionsArgsForCall)
}

func (fake *FakePromoterImplementation) ValidateOptionsCalls(stub func(*imagepromotera.Options) error) {
	fake.validateOptionsMutex.Lock()
	defer fake.validateOptionsMutex.Unlock()
	fake.ValidateOptionsStub = stub
}

func (fake *FakePromoterImplementation) ValidateOptionsArgsForCall(i int) *imagepromotera.Options {
	fake.validateOptionsMutex.RLock()
	defer fake.validateOptionsMutex.RUnlock()
	argsForCall := fake.validateOptionsArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *FakePromoterImplementation) ValidateOptionsArgs() []FakePromoterImplementationValidateOptionsArgs {
	fake.validateOptionsMutex.RLock()
	defer fake.validateOptionsMutex.RUnlock()
	args := make([]FakePromoterImplementationValidateOptionsArgs, len(fake.validateOptionsArgsForCall))
	copy(args, fake.validateOptionsArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) ValidateOptionsReturns(result1 error) {
	fake.validateOptionsMutex.Lock()
	defer fake.validateOptionsMutex.Unlock()
	fake.ValidateOptionsStub = nil
	fake.validateOptionsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ValidateOptionsReturnsOnCall(i int, result1 error) {
	fake.validateOptionsMutex.Lock()
	defer fake.validateOptionsMutex.Unlock()
	fake.ValidateOptionsStub = nil
	if fake.validateOptionsReturnsOnCall == nil {
		fake.validateOptionsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOptionsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) ValidateStagingSignatures(arg1 context.Context, arg2 *imagepromotera.Options, arg3 map[promotion.Edge]any, arg4 map[string]*provenance.Discovery) (promotion.StagingSignatures, error) {
	fake.validateStagingSignaturesMutex.Lock()
	ret, specificReturn := fake.validateStagingSignaturesReturnsOnCall[len(fake.validateStagingSignaturesArgsForCall)]
	fake.validateStagingSignaturesArgsForCall = append(fake.validateStagingSignaturesArgsForCall, FakePromoterImplementationValidateStagingSignaturesArgs{arg1, arg2, arg3, arg4})
	stub := fake.ValidateStagingSignaturesStub
	fakeReturns := fake.validateStagingSignaturesReturns
	fake.recordInvocation("ValidateStagingSignatures", []interface{}{arg1, arg2, arg3, arg4})
	fake.validateStagingSignaturesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesCallCount() int {
	fake.validateStagingSignaturesMutex.RLock()
	defer fake.validateStagingSignaturesMutex.RUnlock()
	return len(fake.validateStagingSignaturesArgsForCall)
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesCalls(stub func(context.Context, *imagepromotera.Options, map[promotion.Edge]any, map[string]*provenance.Discovery) (promotion.StagingSignatures, error)) {
	fake.validateStagingSignaturesMutex.Lock()
	defer fake.validateStagingSignaturesMutex.Unlock()
	fake.ValidateStagingSignaturesStub = stub
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesArgsForCall(i int) (context.Context, *imagepromotera.Options, map[promotion.Edge]any, map[string]*provenance.Discovery) {
	fake.validateStagingSignaturesMutex.RLock()
	defer fake.validateStagingSignaturesMutex.RUnlock()
	argsForCall := fake.validateStagingSignaturesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesArgs() []FakePromoterImplementationValidateStagingSignaturesArgs {
	fake.validateStagingSignaturesMutex.RLock()
	defer fake.validateStagingSignaturesMutex.RUnlock()
	args := make([]FakePromoterImplementationValidateStagingSignaturesArgs, len(fake.validateStagingSignaturesArgsForCall))
	copy(args, fake.validateStagingSignaturesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesReturns(result1 promotion.StagingSignatures, result2 error) {
	fake.validateStagingSignaturesMutex.Lock()
	defer fake.validateStagingSignaturesMutex.Unlock()
	fake.ValidateStagingSignaturesStub = nil
	fake.validateStagingSignaturesReturns = struct {
		result1 promotion.StagingSignatures
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) ValidateStagingSignaturesReturnsOnCall(i int, result1 promotion.StagingSignatures, result2 error) {
	fake.validateStagingSignaturesMutex.Lock()
	defer fake.validateStagingSignaturesMutex.Unlock()
	fake.ValidateStagingSignaturesStub = nil
	if fake.validateStagingSignaturesReturnsOnCall == nil {
		fake.validateStagingSignaturesReturnsOnCall = make(map[int]struct {
			result1 promotion.StagingSignatures
			result2 error
		})
	}
	fake.validateStagingSignaturesReturnsOnCall[i] = struct {
		result1 promotion.StagingSignatures
		result2 error
	}{result1, result2}
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestations(arg1 context.Context, arg2 *imagepromotera.Options, arg3 []schema.Manifest, arg4 map[promotion.Edge]any, arg5 provenance.Generator) error {
	var arg3Copy []schema.Manifest
	if arg3 != nil {
		arg3Copy = make([]schema.Manifest, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.writeProvenanceAttestationsMutex.Lock()
	ret, specificReturn := fake.writeProvenanceAttestationsReturnsOnCall[len(fake.writeProvenanceAttestationsArgsForCall)]
	fake.writeProvenanceAttestationsArgsForCall = append(fake.writeProvenanceAttestationsArgsForCall, FakePromoterImplementationWriteProvenanceAttestationsArgs{arg1, arg2, arg3Copy, arg4, arg5})
	stub := fake.WriteProvenanceAttestationsStub
	fakeReturns := fake.writeProvenanceAttestationsReturns
	fake.recordInvocation("WriteProvenanceAttestations", []interface{}{arg1, arg2, arg3Copy, arg4, arg5})
	fake.writeProvenanceAttestationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsCallCount() int {
	fake.writeProvenanceAttestationsMutex.RLock()
	defer fake.writeProvenanceAttestationsMutex.RUnlock()
	return len(fake.writeProvenanceAttestationsArgsForCall)
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsCalls(stub func(context.Context, *imagepromotera.Options, []schema.Manifest, map[promotion.Edge]any, provenance.Generator) error) {
	fake.writeProvenanceAttestationsMutex.Lock()
	defer fake.writeProvenanceAttestationsMutex.Unlock()
	fake.WriteProvenanceAttestationsStub = stub
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsArgsForCall(i int) (context.Context, *imagepromotera.Options, []schema.Manifest, map[promotion.Edge]any, provenance.Generator) {
	fake.writeProvenanceAttestationsMutex.RLock()
	defer fake.writeProvenanceAttestationsMutex.RUnlock()
	argsForCall := fake.writeProvenanceAttestationsArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsArgs() []FakePromoterImplementationWriteProvenanceAttestationsArgs {
	fake.writeProvenanceAttestationsMutex.RLock()
	defer fake.writeProvenanceAttestationsMutex.RUnlock()
	args := make([]FakePromoterImplementationWriteProvenanceAttestationsArgs, len(fake.writeProvenanceAttestationsArgsForCall))
	copy(args, fake.writeProvenanceAttestationsArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsReturns(result1 error) {
	fake.writeProvenanceAttestationsMutex.Lock()
	defer fake.writeProvenanceAttestationsMutex.Unlock()
	fake.WriteProvenanceAttestationsStub = nil
	fake.writeProvenanceAttestationsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) WriteProvenanceAttestationsReturnsOnCall(i int, result1 error) {
	fake.writeProvenanceAttestationsMutex.Lock()
	defer fake.writeProvenanceAttestationsMutex.Unlock()
	fake.WriteProvenanceAttestationsStub = nil
	if fake.writeProvenanceAttestationsReturnsOnCall == nil {
		fake.writeProvenanceAttestationsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeProvenanceAttestationsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) WriteVerificationSummaries(arg1 context.Context, arg2 *imagepromotera.Options, arg3 []schema.Manifest, arg4 map[promotion.Edge]any, arg5 map[string]*provenance.Discovery, arg6 map[string]*provenance.ImageProvenance) error {
	var arg3Copy []schema.Manifest
	if arg3 != nil {
		arg3Copy = make([]schema.Manifest, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.writeVerificationSummariesMutex.Lock()
	ret, specificReturn := fake.writeVerificationSummariesReturnsOnCall[len(fake.writeVerificationSummariesArgsForCall)]
	fake.writeVerificationSummariesArgsForCall = append(fake.writeVerificationSummariesArgsForCall, FakePromoterImplementationWriteVerificationSummariesArgs{arg1, arg2, arg3Copy, arg4, arg5, arg6})
	stub := fake.WriteVerificationSummariesStub
	fakeReturns := fake.writeVerificationSummariesReturns
	fake.recordInvocation("WriteVerificationSummaries", []interface{}{arg1, arg2, arg3Copy, arg4, arg5, arg6})
	fake.writeVerificationSummariesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePromoterImplementation) WriteVerificationSummariesCallCount() int {
	fake.writeVerificationSummariesMutex.RLock()
	defer fake.writeVerificationSummariesMutex.RUnlock()
	return len(fake.writeVerificationSummariesArgsForCall)
}

func (fake *FakePromoterImplementation) WriteVerificationSummariesCalls(stub func(context.Context, *imagepromotera.Options, []schema.Manifest, map[promotion.Edge]any, map[string]*provenance.Discovery, map[string]*provenance.ImageProvenance) error) {
	fake.writeVerificationSummariesMutex.Lock()
	defer fake.writeVerificationSummariesMutex.Unlock()
	fake.WriteVerificationSummariesStub = stub
}

func (fake *FakePromoterImplementation) WriteVerificationSummariesArgsForCall(i int) (context.Context, *imagepromotera.Options, []schema.Manifest, map[promotion.Edge]any, map[string]*provenance.Discovery, map[string]*provenance.ImageProvenance) {
	fake.writeVerificationSummariesMutex.RLock()
	defer fake.writeVerificationSummariesMutex.RUnlock()
	argsForCall := fake.writeVerificationSummariesArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5, argsForCall.Arg6
}

func (fake *FakePromoterImplementation) WriteVerificationSummariesArgs() []FakePromoterImplementationWriteVerificationSummariesArgs {
	fake.writeVerificationSummariesMutex.RLock()
	defer fake.writeVerificationSummariesMutex.RUnlock()
	args := make([]FakePromoterImplementationWriteVerificationSummariesArgs, len(fake.writeVerificationSummariesArgsForCall))
	copy(args, fake.writeVerificationSummariesArgsForCall)
	return args
}

func (fake *FakePromoterImplementation) WriteVerificationSummariesReturns(result1 error) {
	fake.writeVerificationSummariesMutex.Lock()
	defer fake.writeVerificationSummariesMutex.Unlock()
	fake.WriteVerificationSummariesStub = nil
	fake.writeVerificationSummariesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) WriteVerificationSummariesReturnsOnCall(i int, result1 error) {
	fake.writeVerificationSummariesMutex.Lock()
	defer fake.writeVerificationSummariesMutex.Unlock()
	fake.WriteVerificationSummariesStub = nil
	if fake.writeVerificationSummariesReturnsOnCall == nil {
		fake.writeVerificationSummariesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.writeVerificationSummariesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePromoterImplementation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePromoterImplementation) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakePromoterImplementation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
