// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: promotion_record.proto

package provenance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromotionRecord captures the details of a single image promotion
// for provenance generation.
type PromotionRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// src_ref is the fully qualified source image reference.
	SrcRef string `protobuf:"bytes,1,opt,name=src_ref,json=srcRef,proto3" json:"src_ref,omitempty"`
	// dst_ref is the fully qualified destination image reference.
	DstRef string `protobuf:"bytes,2,opt,name=dst_ref,json=dstRef,proto3" json:"dst_ref,omitempty"`
	// digest is the image digest (e.g., "sha256:abc...").
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// timestamp is when the promotion occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// builder_id identifies the promotion system
	// (e.g., "https://k8s.io/promo-tools@v4.0.8").
	BuilderId string `protobuf:"bytes,5,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	// tags are the tags promoted for the digest, sorted. Empty when the
	// digest was promoted without a tag.
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// source is the promoted staging image.
	Source *ResourceDescriptor `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	// destination is the production image, named by its registry.k8s.io
	// reference.
	Destination *ResourceDescriptor `protobuf:"bytes,8,opt,name=destination,proto3" json:"destination,omitempty"`
	// manifest is the promoter manifest the digest was read from, with the
	// commit of the repository holding it. Unset when the manifest is not
	// known.
	Manifest *ResourceDescriptor `protobuf:"bytes,9,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// promoter describes the promoter binary.
	Promoter *Promoter `protobuf:"bytes,10,opt,name=promoter,proto3" json:"promoter,omitempty"`
	// job describes the CI job running the promotion. Unset outside of Prow.
	Job           *Job `protobuf:"bytes,11,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionRecord) Reset() {
	*x = PromotionRecord{}
	mi := &file_promotion_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionRecord) ProtoMessage() {}

func (x *PromotionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionRecord.ProtoReflect.Descriptor instead.
func (*PromotionRecord) Descriptor() ([]byte, []int) {
	return file_promotion_record_proto_rawDescGZIP(), []int{0}
}

func (x *PromotionRecord) GetSrcRef() string {
	if x != nil {
		return x.SrcRef
	}
	return ""
}

func (x *PromotionRecord) GetDstRef() string {
	if x != nil {
		return x.DstRef
	}
	return ""
}

func (x *PromotionRecord) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PromotionRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PromotionRecord) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

func (x *PromotionRecord) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PromotionRecord) GetSource() *ResourceDescriptor {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PromotionRecord) GetDestination() *ResourceDescriptor {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *PromotionRecord) GetManifest() *ResourceDescriptor {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *PromotionRecord) GetPromoter() *Promoter {
	if x != nil {
		return x.Promoter
	}
	return nil
}

func (x *PromotionRecord) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// ResourceDescriptor mirrors the fields of the in-toto attestation
// ResourceDescriptor used here, so that they serialize the same way:
// https://github.com/in-toto/attestation/blob/main/spec/v1/resource_descriptor.md
type ResourceDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the resource, for example an image reference or a
	// file path relative to the repository root.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// uri locates the resource, for example the repository URL.
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// digest maps algorithms to digests, for example "sha256" or
	// "gitCommit".
	Digest        map[string]string `protobuf:"bytes,3,rep,name=digest,proto3" json:"digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDescriptor) Reset() {
	*x = ResourceDescriptor{}
	mi := &file_promotion_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor) ProtoMessage() {}

func (x *ResourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return file_promotion_record_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceDescriptor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ResourceDescriptor) GetDigest() map[string]string {
	if x != nil {
		return x.Digest
	}
	return nil
}

// Promoter describes the promoter binary.
type Promoter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the promoter version (e.g., "v4.6.0").
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// git_commit is the promoter source commit.
	GitCommit     string `protobuf:"bytes,2,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promoter) Reset() {
	*x = Promoter{}
	mi := &file_promotion_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promoter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promoter) ProtoMessage() {}

func (x *Promoter) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promoter.ProtoReflect.Descriptor instead.
func (*Promoter) Descriptor() ([]byte, []int) {
	return file_promotion_record_proto_rawDescGZIP(), []int{2}
}

func (x *Promoter) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Promoter) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

// Job describes the Prow job running the promotion.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the Prow job name (JOB_NAME).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is the Prow job type (JOB_TYPE), for example "postsubmit".
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// build_id is the Prow build ID (BUILD_ID).
	BuildId string `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// prow_job_id is the Prow job ID (PROW_JOB_ID).
	ProwJobId     string `protobuf:"bytes,4,opt,name=prow_job_id,json=prowJobId,proto3" json:"prow_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_promotion_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_promotion_record_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *Job) GetProwJobId() string {
	if x != nil {
		return x.ProwJobId
	}
	return ""
}

var File_promotion_record_proto protoreflect.FileDescriptor

const file_promotion_record_proto_rawDesc = "" +
	"\n" +
	"\x16promotion_record.proto\x12\x19promo_tools.provenance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x04\n" +
	"\x0fPromotionRecord\x12\x17\n" +
	"\asrc_ref\x18\x01 \x01(\tR\x06srcRef\x12\x17\n" +
	"\adst_ref\x18\x02 \x01(\tR\x06dstRef\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x05 \x01(\tR\tbuilderId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12E\n" +
	"\x06source\x18\a \x01(\v2-.promo_tools.provenance.v1.ResourceDescriptorR\x06source\x12O\n" +
	"\vdestination\x18\b \x01(\v2-.promo_tools.provenance.v1.ResourceDescriptorR\vdestination\x12I\n" +
	"\bmanifest\x18\t \x01(\v2-.promo_tools.provenance.v1.ResourceDescriptorR\bmanifest\x12?\n" +
	"\bpromoter\x18\n" +
	" \x01(\v2#.promo_tools.provenance.v1.PromoterR\bpromoter\x120\n" +
	"\x03job\x18\v \x01(\v2\x1e.promo_tools.provenance.v1.JobR\x03job\"\xc8\x01\n" +
	"\x12ResourceDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12Q\n" +
	"\x06digest\x18\x03 \x03(\v29.promo_tools.provenance.v1.ResourceDescriptor.DigestEntryR\x06digest\x1a9\n" +
	"\vDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\bPromoter\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x02 \x01(\tR\tgitCommit\"h\n" +
	"\x03Job\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12\x1e\n" +
	"\vprow_job_id\x18\x04 \x01(\tR\tprowJobIdB6Z4sigs.k8s.io/promo-tools/v4/promoter/image/provenanceb\x06proto3"

var (
	file_promotion_record_proto_rawDescOnce sync.Once
	file_promotion_record_proto_rawDescData []byte
)

func file_promotion_record_proto_rawDescGZIP() []byte {
	file_promotion_record_proto_rawDescOnce.Do(func() {
		file_promotion_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promotion_record_proto_rawDesc), len(file_promotion_record_proto_rawDesc)))
	})
	return file_promotion_record_proto_rawDescData
}

var file_promotion_record_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_promotion_record_proto_goTypes = []any{
	(*PromotionRecord)(nil),       // 0: promo_tools.provenance.v1.PromotionRecord
	(*ResourceDescriptor)(nil),    // 1: promo_tools.provenance.v1.ResourceDescriptor
	(*Promoter)(nil),              // 2: promo_tools.provenance.v1.Promoter
	(*Job)(nil),                   // 3: promo_tools.provenance.v1.Job
	nil,                           // 4: promo_tools.provenance.v1.ResourceDescriptor.DigestEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_promotion_record_proto_depIdxs = []int32{
	5, // 0: promo_tools.provenance.v1.PromotionRecord.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: promo_tools.provenance.v1.PromotionRecord.source:type_name -> promo_tools.provenance.v1.ResourceDescriptor
	1, // 2: promo_tools.provenance.v1.PromotionRecord.destination:type_name -> promo_tools.provenance.v1.ResourceDescriptor
	1, // 3: promo_tools.provenance.v1.PromotionRecord.manifest:type_name -> promo_tools.provenance.v1.ResourceDescriptor
	2, // 4: promo_tools.provenance.v1.PromotionRecord.promoter:type_name -> promo_tools.provenance.v1.Promoter
	3, // 5: promo_tools.provenance.v1.PromotionRecord.job:type_name -> promo_tools.provenance.v1.Job
	4, // 6: promo_tools.provenance.v1.ResourceDescriptor.digest:type_name -> promo_tools.provenance.v1.ResourceDescriptor.DigestEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_promotion_record_proto_init() }
func file_promotion_record_proto_init() {
	if File_promotion_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promotion_record_proto_rawDesc), len(file_promotion_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_promotion_record_proto_goTypes,
		DependencyIndexes: file_promotion_record_proto_depIdxs,
		MessageInfos:      file_promotion_record_proto_msgTypes,
	}.Build()
	File_promotion_record_proto = out.File
	file_promotion_record_proto_goTypes = nil
	file_promotion_record_proto_depIdxs = nil
}
