// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: promotion_record.proto

package provenance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PromotionRecord captures the details of a single image promotion
// for provenance generation.
type PromotionRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// src_ref is the fully qualified source image reference.
	SrcRef string `protobuf:"bytes,1,opt,name=src_ref,json=srcRef,proto3" json:"src_ref,omitempty"`
	// dst_ref is the fully qualified destination image reference.
	DstRef string `protobuf:"bytes,2,opt,name=dst_ref,json=dstRef,proto3" json:"dst_ref,omitempty"`
	// digest is the image digest (e.g., "sha256:abc...").
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// timestamp is when the promotion occurred.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// builder_id identifies the promotion system
	// (e.g., "https://k8s.io/promo-tools@v4.0.8").
	BuilderId     string `protobuf:"bytes,5,opt,name=builder_id,json=builderId,proto3" json:"builder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionRecord) Reset() {
	*x = PromotionRecord{}
	mi := &file_promotion_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionRecord) ProtoMessage() {}

func (x *PromotionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_promotion_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionRecord.ProtoReflect.Descriptor instead.
func (*PromotionRecord) Descriptor() ([]byte, []int) {
	return file_promotion_record_proto_rawDescGZIP(), []int{0}
}

func (x *PromotionRecord) GetSrcRef() string {
	if x != nil {
		return x.SrcRef
	}
	return ""
}

func (x *PromotionRecord) GetDstRef() string {
	if x != nil {
		return x.DstRef
	}
	return ""
}

func (x *PromotionRecord) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PromotionRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PromotionRecord) GetBuilderId() string {
	if x != nil {
		return x.BuilderId
	}
	return ""
}

var File_promotion_record_proto protoreflect.FileDescriptor

const file_promotion_record_proto_rawDesc = "" +
	"\n" +
	"\x16promotion_record.proto\x12\x19promo_tools.provenance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x0fPromotionRecord\x12\x17\n" +
	"\asrc_ref\x18\x01 \x01(\tR\x06srcRef\x12\x17\n" +
	"\adst_ref\x18\x02 \x01(\tR\x06dstRef\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"builder_id\x18\x05 \x01(\tR\tbuilderIdB6Z4sigs.k8s.io/promo-tools/v4/promoter/image/provenanceb\x06proto3"

var (
	file_promotion_record_proto_rawDescOnce sync.Once
	file_promotion_record_proto_rawDescData []byte
)

func file_promotion_record_proto_rawDescGZIP() []byte {
	file_promotion_record_proto_rawDescOnce.Do(func() {
		file_promotion_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_promotion_record_proto_rawDesc), len(file_promotion_record_proto_rawDesc)))
	})
	return file_promotion_record_proto_rawDescData
}

var file_promotion_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_promotion_record_proto_goTypes = []any{
	(*PromotionRecord)(nil),       // 0: promo_tools.provenance.v1.PromotionRecord
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_promotion_record_proto_depIdxs = []int32{
	1, // 0: promo_tools.provenance.v1.PromotionRecord.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_promotion_record_proto_init() }
func file_promotion_record_proto_init() {
	if File_promotion_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_promotion_record_proto_rawDesc), len(file_promotion_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_promotion_record_proto_goTypes,
		DependencyIndexes: file_promotion_record_proto_depIdxs,
		MessageInfos:      file_promotion_record_proto_msgTypes,
	}.Build()
	File_promotion_record_proto = out.File
	file_promotion_record_proto_goTypes = nil
	file_promotion_record_proto_depIdxs = nil
}
